# -Dspring.profiles.active=heroku
spring.thymeleaf.cache: false
spring:
  datasource:
    url: ${DB_URL}
    username: uidzwjegjixbgv
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
    maxTotal: 10
  http:
    multipart:
      maxFileSize: 4MB
      maxRequestSize: 4MB
#logging.level.root: DEBUG
#logging.level.org.hibernate: DEBUG
