# -Dspring.profiles.active=pg
spring.thymeleaf.cache: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/genogram
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
    maxTotal: 10
  http:
    multipart:
      maxFileSize: 4MB
      maxRequestSize: 4MB
#logging.level.root: DEBUG
logging.level.org.hibernate: DEBUG
