spring.thymeleaf.cache: false
spring:
  datasource:
    url: jdbc:db2://localhost:50000/GENOGRAM
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: com.ibm.db2.jcc.DB2Driver
    maxTotal: 10
  http:
    multipart:
      maxFileSize: 4MB
      maxRequestSize: 4MB
#logging.level.root: DEBUG
logging.level.org.hibernate: DEBUG
