CREATE DATABASE genogram
CREATE REGULAR TABLESPACE genogram

-- DB2
LIST DB DIRECTORY
SELECT SCHEMANAME FROM SYSCAT.SCHEMATA
SELECT TBSPACEID, TBSPACE FROM syscat.tablespaces
CONNECT TO GENOGRAM
SELECT TBSPACEID, TBSPACE, TABLEID, TABNAME FROM syscat.tables WHERE TBSPACE = 'GENOGRAM'
SELECT DISTINCT TBSPACEID, TABNAME FROM syscat.tables WHERE TABNAME = 'DIAGRAM'
LIST TABLES FOR SCHEMA DSS
-- DB2 version
SELECT INSTANCEINFO.SERVICE_LEVEL FROM TABLE(ENV_GET_INST_INFO()) AS INSTANCEINFO
-- SQL0668N
REORG TABLE diagram
REORG TABLE person
