var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;
$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};e.prototype.createResolveAndReject_=
function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(m){f(m)}}:b}var d,f,g=new e(function(a,
b){d=a;f=b});this.callWhenSettled_(c(a,d),c(b,f));return g};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(function(){f.asyncExecute(c)})};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
d){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())c(f.value).callWhenSettled_(b,d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function f(b){return function(c){g[b]=c;k--;0==k&&a(g)}}var g=[],k=0;do g.push(void 0),k++,c(d.value).callWhenSettled_(f(g.length-1),e),d=b.next();while(!d.done)})};return e},"es6-impl","es3");
$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6-impl","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;for(c=c||0;c<e;c++)if(b[c]==a||Object.is(b[c],a))return!0;return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6-impl","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
$jscomp.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6-impl","es3");$jscomp.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6-impl","es3");$jscomp.polyfill("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991},"es6-impl","es3");var AjaxUtils=function(){};
AjaxUtils.fetch=function(a,b){return"function"===typeof fetch?fetch(a,{method:"post",body:b,credentials:"include"}).then(function(a){return a.json()}):new Promise(function(c,d){var e=new XMLHttpRequest;e.open("post",a);e.withCredentials=!0;e.addEventListener("loadend",function(){200<=e.status&&300>e.status?c(JSON.parse(e.response)):d(e.statusText)});e.send(b)})};AjaxUtils.post=function(a,b){return AjaxUtils.fetch(a,b)};var FormUtils=function(){};
FormUtils.listInputElements=function(a){var b=[],c=a.querySelectorAll("input");a=a.querySelectorAll("textarea");Array.prototype.forEach.call(c,function(a){b.push(a)});Array.prototype.forEach.call(a,function(a){b.push(a)});return b};FormUtils.load=function(a,b){FormUtils.listInputElements(a).forEach(function(a){var c=a.getAttribute("name"),e=a.getAttribute("type"),c=b[c];"radio"==e?$(a).val([c]).checkboxradio("refresh"):"checkbox"==e?(a.checked=0<c,$(a).flipswitch("refresh")):a.value=c})};
FormUtils.enableButton=function(a,b){null!=a&&(void 0===b||b?($(a).removeClass("ui-state-disabled"),a.removeAttribute("disabled")):($(a).addClass("ui-state-disabled"),a.setAttribute("disabled","disabled")))};var Tally=function(){};Tally.reset=function(a){Tally.val=void 0===a?0:a};Tally.increment=function(){return++Tally.val};Tally.val=0;var AlphabeticalTally=function(){};
AlphabeticalTally.increment=function(){for(var a="",b=AlphabeticalTally.val++,c=AlphabeticalTally.Max,d=0;2>d;d++)var e=String.fromCharCode(65+b%c),b=Math.floor(b/c),a=e+a;return a};AlphabeticalTally.val=0;AlphabeticalTally.Max=26;var UUID=function(){};UUID.toString=function(){return UUID.Format.replace(/X|Y/g,function(a){var b=16*Math.random()|0;return("X"===a?b:b&3|8).toString(16)})};UUID.Format="XXXXXXXX-XXXX-4XXX-YXXX-XXXXXXXXXXXX";
var EntityBase=function(a){this.base=document.querySelector("base").getAttribute("href")+a};EntityBase.prototype.list=function(a){a=void 0===a?{}:a;return AjaxUtils.post(this.base+"/list",a)};EntityBase.prototype.select=function(a){var b=new FormData;b.append("id",a);return AjaxUtils.post(this.base+"/select",b)};EntityBase.prototype.save=function(a){return AjaxUtils.post(this.base+"/save",a)};var DiagramEntity=function(){EntityBase.call(this,"diagram")};$jscomp.inherits(DiagramEntity,EntityBase);
var AbstractPane=function(a,b){this.pane=document.getElementById(a);this.form=this.pane.querySelector("form");this.editor=b;this.isPanel=b.isPanel};AbstractPane.prototype.setupEvents=function(){this.isPanel&&$(this.pane).panel({beforeclose:function(){}})};AbstractPane.prototype.enableButton=function(a,b){FormUtils.enableButton(a,void 0===b?!0:b)};AbstractPane.prototype.disableButton=function(a){this.enableButton(a,!1)};
AbstractPane.prototype.showPane=function(a){a=void 0===a?"right":a;if(this.isPanel){var b=$("#"+this.pane.id);EditorMain.PANEL_DODGE&&(b.panel("destroy"),b.panel({position:a}));b.panel("open")}else $(this.pane).show()};AbstractPane.prototype.hidePane=function(){this.isPanel?$(this.pane).panel("close"):$(this.pane).hide()};
var EnclosurePopup=function(){this.popup=document.getElementById("enclosurePopup");this.form=this.popup.querySelector("form");this.plusButton=this.popup.querySelector(".ui-icon-plus");this.minusButton=this.popup.querySelector(".ui-icon-minus");this.setupEvents()};
EnclosurePopup.prototype.setupEvents=function(){var a=this,b=this.popup.querySelector(".ui-icon-delete:not(.ui-btn-icon-notext)");$("[name=lineStyle]").click(function(b){a.target.parent.lineStyle=b.target.value});this.plusButton.addEventListener("click",function(){a.target.increase()});this.minusButton.addEventListener("click",function(){a.target.parent.delHandle(a.target);$(a.popup).popup("close")});b.addEventListener("click",function(){a.target.parent.eject();$(a.popup).popup("close")});$(this.popup).popup({afterclose:function(){Field.Instance.clearSelection()}})};
EnclosurePopup.prototype.setupForm=function(){var a=this.target.listAll.length;FormUtils.load(this.form,this.target);FormUtils.enableButton(this.minusButton,3<a)};EnclosurePopup.prototype.open=function(a){Field.Instance.addTarget(a.parent);this.target=a;this.setupForm();$(this.popup).popup("open",{})};var InputPanel=function(a){AbstractPane.call(this,"inputPanel",a);this.partnerView=document.getElementById("partnerView");this.person=null;this.setupEvents()};$jscomp.inherits(InputPanel,AbstractPane);
InputPanel.prototype.setupEvents=function(){var a=this;AbstractPane.prototype.setupEvents.call(this);var b=this.pane.querySelector('[name="name"]'),c=this.pane.querySelector('[name="description"]'),d=$('[name="gender"]'),e=this.pane.querySelector('[name="dob"]'),f=this.pane.querySelector('[name="dod"]'),g=this.pane.querySelector('[name="death"]'),h=this.pane.querySelector('[name="age"]');b.addEventListener("keyup",function(){a.person.name=b.value});c.addEventListener("keyup",function(){a.person.description=
c.value});d.click(function(b){a.person.gender=b.target.value;a.refreshControls()});e.addEventListener("keyup",function(){var b=(new GenoCalendar(e.value)).toString();a.person.dob=b;h.value=a.person.age});e.addEventListener("change",function(){var a=new GenoCalendar(e.value);e.value=a.toString()});f.addEventListener("keyup",function(){var b=(new GenoCalendar(f.value)).toString();a.person.dod=b;h.value=a.person.age});f.addEventListener("change",function(){var a=new GenoCalendar(f.value);f.value=a.toString()});
$(g).bind("change",function(){a.person.death=g.checked?1:0;g.checked||(f.value="",a.person.dod="")});h.addEventListener("keyup",function(){return a.ageChanged()});this.setupAttrEvents();this.setupButtonEvents()};
InputPanel.prototype.setupAttrEvents=function(){var a=this,b=this.pane.querySelector('[name="illness"]'),c=this.pane.querySelector('[name="abuse"]'),d=this.pane.querySelector('[name="attr"]');$(b).bind("change",function(){a.person.illness=b.checked?1:0});$(c).bind("change",function(){a.person.abuse=c.checked?1:0});d.addEventListener("keyup",function(){a.person.attr=d.value})};
InputPanel.prototype.setupButtonEvents=function(){var a=this;this.parentsButton=document.getElementById("parentsButton");this.partnerButton=document.getElementById("partnerButton");this.parentsButton.addEventListener("click",function(){return a.addParents()});this.partnerButton.addEventListener("click",function(){return a.addPartner()});this.upButton=document.getElementById("upButton");this.upButton.addEventListener("click",function(){return a.moveUp()});this.downButton=document.getElementById("downButton");
this.downButton.addEventListener("click",function(){return a.moveDown()});this.deleteButton=this.pane.querySelector('[name="deleteButton"]');this.deleteButton.addEventListener("click",function(){a.person.remove();a.editor.closePane()})};
InputPanel.prototype.ageChanged=function(){var a=this.pane.querySelector('[name="dob"]');this.pane.querySelector('[name="dod"]');var b=this.pane.querySelector('[name="age"]'),b=parseInt(b.value);this.person.age=null;if(isNaN(b))a.value=null,this.person.dob=null;else{var c=(new Date).getFullYear()-b;a.value=c;this.person.dob=c;this.person.age=b}this.refreshControls()};
InputPanel.prototype.addParents=function(){var a=Field.Instance;if(this.person.generation==a.minGeneration&&a.numOfGeneration==Field.MAX_GENERATION)MessagePopup.open("msg.generations");else{var b=new Person("m"),c=new Person("f"),a=a.createPair(b,c);this.person.addParents(a);this.refreshControls()}};InputPanel.prototype.addPartner=function(){var a=Field.Instance,b=new Person(this.person.isMale?"f":"m"),a=a.createPair(this.person,b);this.person.addPartner(a);this.setupPartner();this.refreshControls()};
InputPanel.prototype.moveUp=function(){this.person.moveUp();this.refreshControls();Field.Instance.dirty=!0};InputPanel.prototype.moveDown=function(){this.person.moveDown();this.refreshControls();Field.Instance.dirty=!0};InputPanel.prototype.moveLeft=function(){this.person.moveLeft();this.refreshControls();Field.Instance.dirty=!0};InputPanel.prototype.moveRight=function(){this.person.moveRight();this.refreshControls();Field.Instance.dirty=!0};
InputPanel.prototype.refreshControls=function(){var a=this.person.gender,b=this.person.age,c=this.person.parents,d=c&&c.leftSide.ay+2<this.person.ay,a=("f"==a||"m"==a)&&null==b||Person.MarriageableAge<b,b=this.person.relationList.length;this.pane.querySelector('[name="deleteButton"]');0==b?$('[name="gender"]').checkboxradio("enable"):$('[name="gender"]').checkboxradio("disable");this.enableButton(this.parentsButton,!this.person.parents);this.enableButton(this.partnerButton,a);this.enableButton(this.upButton,
d);this.enableButton(this.downButton,c);this.enableButton(this.deleteButton,this.person.removable)};InputPanel.prototype.setupPartner=function(){var a=this,b=this.partnerView;b.textContent=null;this.person.relationList.forEach(function(c){c=c.getPartner(a.person);var d=document.createElement("span"),e=document.createElement("a"),f=document.createElement("li");d.textContent=c.info;e.appendChild(d);f.appendChild(e);f.setAttribute("data-id",c.id);f.setAttribute("data-icon",!1);b.appendChild(f)});$(b).listview("refresh")};
InputPanel.prototype.setupForm=function(){var a=Field.Instance;FormUtils.load(this.form,this.person);this.setupPartner();this.refreshControls();a.addTarget(this.person)};InputPanel.prototype.open=function(a){var b=Field.Instance.center<a.ax?"left":"right";this.person=a;this.setupForm();this.showPane(b)};
var ListviewRow=function(a,b){b=void 0===b?null:b;var c=document.createElement("img"),d=document.createElement("span"),e=document.createElement("p"),f=document.createElement("a"),g=document.createElement("li");null!=b&&c.setAttribute("src",b);d.textContent=a.name;e.textContent=a.description;a.href&&f.setAttribute("href",a.href);f.appendChild(c);f.appendChild(d);f.appendChild(e);a.count&&(b=document.createElement("span"),b.classList.add("ui-li-count"),b.textContent=a.count,f.appendChild(b));g.appendChild(f);
this.img=c;this.anchor=f;this.li=g},MessagePopup=function(){};MessagePopup.open=function(a){var b=document.getElementById("messagePopup").querySelectorAll("pre");Array.prototype.forEach.call(b,function(b){b.id==a?$(b).show():$(b).hide()});$(messagePopup).popup("open",{})};var PartnerPanel=function(a){AbstractPane.call(this,"partnerPanel",a);this.childrenView=document.getElementById("childrenView");this.relation=null;this.setupEvents()};$jscomp.inherits(PartnerPanel,AbstractPane);
PartnerPanel.prototype.setupEvents=function(){var a=this;AbstractPane.prototype.setupEvents.call(this);var b=document.getElementById("widelyButton"),c=document.getElementById("mChildButton"),d=document.getElementById("fChildButton");$('[name="relationType"]').click(function(){var b=$('[name="relationType"]:checked').val();a.relation.type=b});this.narrowlyButton=document.getElementById("narrowlyButton");this.narrowlyButton.addEventListener("click",function(){a.relation.narrowly();a.relation.reassignChildren();
a.refreshControls();Field.Instance.dirty=!0});b.addEventListener("click",function(){a.relation.widely();a.relation.reassignChildren();a.refreshControls();Field.Instance.dirty=!0});c.addEventListener("click",function(){a.addChild("m")});d.addEventListener("click",function(){a.addChild("f")});$(this.childrenView).sortable({stop:function(b,c){a.reorganizeChildren()}})};
PartnerPanel.prototype.addChild=function(a){var b=Field.Instance;b.maxGeneration<=this.relation.father.generation&&b.numOfGeneration==Field.MAX_GENERATION?MessagePopup.open("msg.generations"):(a=new Person(a),this.relation.addChild(a),this.relation.reorder(),this.relation.reassignChildren(),this.setupChildren())};PartnerPanel.prototype.makeChainList=function(){var a=[];this.relation.children.forEach(function(b){var c=new Chain;c.copyChainProperties(b);a.push(c)});return a};
PartnerPanel.prototype.makeNewList=function(){var a=[],b={},c=this.childrenView.querySelectorAll("li");this.relation.children.forEach(function(a){b[a.id]=a});Array.prototype.forEach.call(c,function(c,e){c=c.getAttribute("data-id");a.push(b[c])});return a};
PartnerPanel.prototype.reorganizeChildren=function(){var a=this;this.makeChainList();var b=this.makeNewList();[this.relation.children[0].prevActor].concat(b);this.relation.children=[];b.forEach(function(b,d){a.relation.children.push(b);b.bornOrder=a.relation.children.length});$(this.childrenView).listview("refresh");this.relation.reassignChildren();Field.Instance.dirty=!0};
PartnerPanel.prototype.refreshControls=function(){this.enableButton(this.narrowlyButton,2<Math.abs(this.relation.leftSide.ax-this.relation.rightSide.ax))};
PartnerPanel.prototype.setupChildren=function(){var a=this.childrenView;a.textContent=null;this.relation.children.forEach(function(b){var c=document.createElement("span"),d=document.createElement("a"),e=document.createElement("li");c.textContent=b.info;d.appendChild(c);e.appendChild(d);e.setAttribute("data-id",b.id);e.setAttribute("data-icon",!1);a.appendChild(e)});$(a).listview("refresh")};
PartnerPanel.prototype.setupForm=function(){var a=this.pane.querySelector('[name="father"]'),b=this.pane.querySelector('[name="mother"]');a.value=this.relation.father.info;b.value=this.relation.mother.info;$('[name="relationType"]').val([this.relation.type]).checkboxradio("refresh")};PartnerPanel.prototype.open=function(a){var b=Field.Instance.center<a.x?"left":"right";this.relation=a;this.setupForm();this.setupChildren();this.refreshControls();this.showPane(b)};
var RelationPanel=function(a){AbstractPane.call(this,"relationPanel",a);this.flipButton=this.pane.querySelector('[name="flipButton"]');this.deleteButton=this.pane.querySelector('[name="deleteButton"]');this.to=this.from=null;this.setupEvents()};$jscomp.inherits(RelationPanel,AbstractPane);
RelationPanel.prototype.setupEvents=function(){var a=this;AbstractPane.prototype.setupEvents.call(this);$('[name="emotion"]').click(function(){a.deleteRelationship();a.relationship=a.createRelationship();a.resetControls()});this.deleteButton.addEventListener("click",function(){a.deleteRelationship();a.resetControls();a.editor.closePane()});this.flipButton&&this.flipButton.addEventListener("click",function(){return a.flip()})};
RelationPanel.prototype.createRelationship=function(){var a=Field.Instance,b=$('[name="emotion"]:checked'),b=Relationship.create(b.val(),this.from,this.to);b.hit=!0;b.selected=!0;a.addActor(b);a.addTarget(b);return b};RelationPanel.prototype.deleteRelationship=function(){this.relationship&&(this.relationship.eject(),this.relationship=null)};RelationPanel.prototype.flip=function(){this.relationship.flip();this.from=this.relationship.person;this.to=this.relationship.other;this.resetControls()};
RelationPanel.prototype.resetControls=function(){var a=this.pane.querySelector('[name="from"]'),b=this.pane.querySelector('[name="to"]');a.value=this.from.info;b.value=this.to.info;this.enableButton(this.flipButton,this.relationship);this.enableButton(this.deleteButton,this.relationship)};RelationPanel.prototype.setupForm=function(){var a=$('[name="emotion"]');this.relationship?a.val([this.relationship.emotion]).checkboxradio("refresh"):a.removeAttr("checked").checkboxradio("refresh");this.resetControls()};
RelationPanel.prototype.open=function(a,b){b=void 0===b?null:b;var c=Field.Instance;if(b){var d=a.ax+(b.ax-a.ax)/2;this.from=a;this.to=b;this.relationship=null;this.isNew=!0;a=c.center<d?"left":"right"}else this.from=a.person,this.from.hit=!0,this.to=a.other,this.to.hit=!0,this.relationship=a,this.isNew=!1,a=c.center<this.relationship.cx?"left":"right";this.setupForm();this.showPane(a);window.getSelection().collapse(document.body,0)};
var SettingPanel=function(a){this.appMain=a;this.panel=document.getElementById("settingPanel");this.form=this.panel.querySelector("form");this.saveButton=document.getElementById("saveButton");this.setupEvents()};
SettingPanel.prototype.setupEvents=function(){var a=this,b=$('[name="gridSize"]'),c=$('[name="nameSize"]'),d=document.getElementById("encloseButton"),e=document.getElementById("clearButton"),f=document.querySelector("a.yes");b.change(function(){b.val()||(b.val(b.attr("value")),b.slider("refresh"))});c.change(function(){c.val()||(c.val(c.attr("value")),c.slider("refresh"))});null!=d&&d.addEventListener("click",function(){a.addEnclosure()});0<this.appMain.documentId.length&&(this.saveButton.classList.remove("ui-state-disabled"),
this.saveButton.addEventListener("click",function(){a.save()}));null!=e&&e.addEventListener("click",function(){var a=document.getElementById("confirmPopup");$(a).popup("open")});f.addEventListener("click",function(){a.appMain.initSandbox();a.close()});EditorMain.DEBUG&&(document.querySelector('[name="showGrid"]').checked=!0);this.setupPrinting()};
SettingPanel.prototype.setupPrinting=function(){var a=document.querySelector('[name="description"]'),b=document.getElementById("printButton"),c=document.getElementById("printFrame"),d=c.contentWindow;c.style.visibility="hidden";c.style.position="fixed";c.style.right="0";c.style.bottom="0";d.addEventListener("DOMContentLoaded",function(){var e=d.document.querySelector("title"),f=d.document.querySelector("img");e.textContent=a.value;f.addEventListener("load",function(){c.focus();d.focus();console.log("execCommand.");
d.document.execCommand("print",!1,null)||(console.log("win.print()"),d.print())});null!=b&&b.addEventListener("click",function(){f.src=FlexibleView.Instance.canvas.toDataURL()})})};SettingPanel.prototype.loadDiagram=function(a){FormUtils.load(this.form,a)};SettingPanel.prototype.addEnclosure=function(){this.appMain.addEnclosure()};SettingPanel.prototype.createDiagramInfo=function(a){a.append("image",FlexibleView.Instance.canvas.toDataURL())};
SettingPanel.prototype.createPersonList=function(a){var b=this.appMain.field.personList,c=[];b.sort(function(a,b){return a.generation-b.generation});b.forEach(function(b,e){var d=b.parents,g="personList["+e+"].";b.principal&&a.append("personId",b.id);b.appendTo(a,g);console.log(e+":"+b.id);d&&(b=g+"parents.",e=d.id,-1==c.indexOf(d)?c.push(d):e=UUID.toString(),a.append(b+"id",e),a.append(b+"type",d.type),a.append(b+"person.id",d.father.id),a.append(b+"other.id",d.mother.id))})};
SettingPanel.prototype.createPartnerList=function(a){var b=0;this.appMain.field.pairList.forEach(function(c){if(!(0<c.children.length)){var d="partnerList["+b+"].";a.append(d+"id",c.id);a.append(d+"type",c.type);a.append(d+"person.id",c.father.id);a.append(d+"other.id",c.mother.id);b++}})};
SettingPanel.prototype.createRelationshipList=function(a){this.appMain.field.relationshipList.forEach(function(b,c){c="relationshipList["+c+"].";a.append(c+"id",b.id);a.append(c+"emotion",b.emotion);a.append(c+"person.id",b.person.id);a.append(c+"other.id",b.other.id)})};
SettingPanel.prototype.createShapesList=function(a){var b=0;this.appMain.field.shapesList.forEach(function(c){c.createFormData().forEach(function(c){var d="shapesList["+b+"].";a.append(d+"id",c.regId);c.parentId&&a.append(d+"parentId",c.parentId);a.append(d+"type",c.type);a.append(d+"x",c.x);a.append(d+"y",c.y);a.append(d+"lineStyle",c.parent.lineStyle);b++})})};
SettingPanel.prototype.save=function(){var a=this,b=new FormData(this.form),c=new DiagramEntity;this.createDiagramInfo(b);this.createPersonList(b);this.createPartnerList(b);this.createRelationshipList(b);this.createShapesList(b);$.mobile.loading("show");c.save(b).then(function(b){$.mobile.loading("hide");b.ok?($(a.panel).panel("close"),MessagePopup.open("msg.saved")):MessagePopup.open("msg.save.failed")})};SettingPanel.prototype.open=function(){$(this.panel).panel("open")};
SettingPanel.prototype.close=function(){$(this.panel).panel("close")};var Actor=function(a,b,c){this.id=UUID.toString();this.x=void 0===a?0:a;this.y=void 0===b?0:b;this.z=void 0===c?0:c;this.radius=0;this.holdable=!1;this.spawnList=[]};Actor.prototype.reserve=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];this.spawnList=this.spawnList.concat(b)};Actor.prototype.getDistance=function(a){var b=this.x-a.x;a=this.y-a.y;return Math.sqrt(b*b+a*a)};
Actor.prototype.getRadian=function(a){return Math.atan2(this.y-a.y,this.x-a.x)};Actor.prototype.getMidpoint=function(a){return new Actor((this.x+a.x)/2,(this.y+a.y)/2)};Actor.prototype.getInterimPoint=function(a,b,c){var d=this.x-a.x;a=this.y-a.y;b=Math.sqrt(d*d+a*a)*(void 0===b?1:b)/(void 0===c?1:c);d=Math.atan2(a,d);return new Actor(this.x-Math.cos(d)*b,this.y-Math.sin(d)*b)};Actor.prototype.includes=function(a,b,c){c=void 0===c?null:c;a=this.x-a;b=this.y-b;return Math.sqrt(a*a+b*b)<(c?c:this.radius)};
Actor.prototype.isHit=function(a,b){return this.includes(a,b)};Actor.prototype.move=function(a,b){this.x+=a;this.y+=b};Actor.prototype.eject=function(){this.isGone=!0};Actor.prototype.react=function(){return[]};Actor.prototype.draw=function(a){};$jscomp.global.Object.defineProperties(Actor.prototype,{spawn:{configurable:!0,enumerable:!0,get:function(){var a=this.spawnList;this.spawnList=[];return a}}});
var Chain=function(){Actor.call(this,0,0,Chain.Z);this.ry=this.rx=0;this.prevActor=null;this.nextActor=[];this.generation=0};$jscomp.inherits(Chain,Actor);Chain.prototype.copyChainProperties=function(a){this.x=a.x;this.y=a.y;this.rx=a.rx;this.ry=a.ry;this.prevActor=a.prevActor};Chain.prototype.moveQuickly=function(){this.prevActor&&(this.x=this.ax,this.y=this.ay)};
Chain.prototype.ancestorOccupancy=function(a,b){a=void 0===a?new Occupancy:a;b=void 0===b?0:b;var c=a;a=[];0<b&&(this.listPartner(a),a.forEach(function(a){c.merge(new Occupancy(a))}));this.parents&&(this.parents.father.ancestorOccupancy(c,b+1),this.parents.mother.ancestorOccupancy(c,b+1));return c};
Chain.prototype.descendantOccupancy=function(a,b){a=void 0===a?new Occupancy:a;var c=this,d=a;a=[];if(d.isDone(this))return d;d.merge(new Occupancy(this));this.listPartner(a);a.forEach(function(a){a!=c&&a.descendantOccupancy(d)});this.relationList.forEach(function(a){a.children.forEach(function(a){a.descendantOccupancy(d)})});return d};
Chain.prototype.getOccupancy=function(){var a=this,b=this.descendantOccupancy();if(!this.isMale&&1==this.bornOrder)return b;var c=[];this.listPartner(c);c.forEach(function(c){c!=a&&c.ancestorOccupancy(b)});return b};Chain.prototype.listOccupancy=function(a){this.relationList.forEach(function(a){});return{left:1,right:1}};
Chain.prototype.separate=function(a,b){b=void 0===b?1:b;if(this.rest&&a.rest){var c=0>b?-1:1,d=a.ax-this.ax;this.prevActor==a?(console.log("separate:this:"+d),this.rx-=c,8<Math.abs(this.rx)&&(console.log("**error** #separate.this/rx:"+this.rx),this.rx%=8)):a.prevActor==this?(console.log("separate:other:"+b),a.rx+=c):(console.log("**error** #separate.else"),console.log(this))}};
Chain.prototype.assignActor=function(a,b,c){c=void 0===c?0:c;this.prevActor!=a&&a.prevActor!=this&&(a.prevActor=this,a.rx=void 0===b?0:b,a.ry=c,a.x=this.ax,a.y=this.ay,a.generation=this.generation,0>c?a.generation--:0<c&&a.generation++,console.log("[Chain#assignActor] "+this.info+":G"+this.generation+" -> "+a.info+":G"+a.generation),this.nextActor.push(a))};
Chain.prototype.addActor=function(a,b,c){c=void 0===c?0:c;console.log("[Chain#addActor:"+this.info+"]"+a.info);var d=this.getNextPartner();a.prevActor=this;a.rx=b;a.ry=c;a.x=this.ax;a.y=this.y;if(d){var e=this.nextActor.indexOf(d);console.log(a.info+" -> "+d.info);d.prevActor=a;d.rx=b;d.ry=c;d.x=a.x+b;a.rx=d.rx;a.ry=d.ry;a.nextActor.push(d);this.nextActor.splice(e,1)}a.generation=this.generation;0>c?a.generation--:0<c&&a.generation++;console.log(this.info+":G"+this.generation+" -> "+a.info+":G"+a.generation);
this.nextActor.push(a)};Chain.prototype.insertActor=function(a,b,c){c=void 0===c?0:c;b=this.prevActor;var d=b.nextActor.indexOf(this);b.nextActor.splice(d,1);b.nextActor.push(a);a.prevActor=b;a.x=b.x;a.y=b.y;a.rx=this.rx;a.ry=this.ry;a.generation=this.generation;0>c?a.generation--:0<c&&a.generation++;a.nextActor.push(this);this.prevActor=a};
Chain.prototype.reassignActor=function(a,b,c){c=void 0===c?null:c;this.prevActor==a&&(this.rx=-b,null!=c&&(this.ry=-c));a.prevActor==this&&(a.rx=b,null!=c&&(a.ry=c))};Chain.prototype.reassignAbsolute=function(a,b){a=void 0===a?null:a;b=void 0===b?null:b;var c=!1;null!=a&&(this.ax!=a&&(c=!0),this.rx=a-this.prevActor.ax);null!=b&&(this.ay!=b&&(c=!0),this.ry=b-this.prevActor.ay);return c};
Chain.prototype.getPrevPartner=function(){var a=this.prevActor;return a instanceof Person&&a.generation==this.generation&&!this.isSibling(a)?a:null};Chain.prototype.getNextPartner=function(){var a=this,b=null;this.nextActor.forEach(function(c){c.generation!=a.generation||a.isSibling(c)||(b=c)});return b};
Chain.prototype.addPartner=function(a){var b=this.getPrevPartner();this.getNextPartner();var c=!1,d=this.isMale?2:-2;this.prevActor!=a&&a.prevActor!=this&&(console.log("Chain#addPartner:"+this.info+"_"+a.info),b&&(c=this.isMale?this.x<b.x:b.x<this.x),c?b.addActor(a,-d):this.addActor(a,d),this.reserve(a))};
$jscomp.global.Object.defineProperties(Chain.prototype,{ax:{configurable:!0,enumerable:!0,get:function(){return this.prevActor?this.prevActor.ax+this.rx:this.x}},ay:{configurable:!0,enumerable:!0,get:function(){return this.prevActor?this.prevActor.ay+this.ry:this.y}},rest:{configurable:!0,enumerable:!0,get:function(){return this.prevActor?this.x==this.ax&&this.y==this.ay:!0}},prevId:{configurable:!0,enumerable:!0,get:function(){return this.prevActor instanceof Person?this.prevActor.id:null}}});
Chain.Z=100;var Ties=function(a){Chain.call(this);this.gender=a;this.parents=null;this.bornOrder=0;this.relationList=[]};$jscomp.inherits(Ties,Chain);Ties.Z=Chain.Z;Ties.prototype.attributeChanged=function(){};Ties.prototype.isSibling=function(a){return this.parents&&a.parents?this.parents==a.parents:!1};Ties.prototype.isPartner=function(a){var b=this,c=!1;this.relationList.forEach(function(d){d.isPair(b,a)&&(c=!0)});return c};
Ties.prototype.addParents=function(a,b){b=void 0===b?!0:b;console.log("Ties#addParents "+a.info);var c=a.leftSide;a.addChild(this,b);c.addPartner(a,b);this.reserve(a.leftSide,a.rightSide)};Ties.prototype.getOrder=function(a){var b=this,c=-1;this.relationList.forEach(function(d,e){b.isMale?d.mother==a&&(c=e):d.father==a&&(c=e)});return c};
Ties.prototype.listPartner=function(a){if(-1==a.indexOf(this)){var b=this.partnerList;this.isMale?a.push(this):b.reverse();b.forEach(function(b){b.listPartner(a)});this.isMale||-1!=a.indexOf(this)||a.push(this)}};Ties.prototype.hasRelation=function(a){return-1!=this.relationList.indexOf(a)};
Ties.prototype.addPartner=function(a,b){b=void 0===b?!0:b;if(this.hasRelation(a))return this.relationList.length;console.log("Ties#addPartner:"+this.info+":"+a.info);var c=this.relationList.unshift(a),d=a.getPartner(this),e=d.hasRelation(a);this.relationList.forEach(function(a,b){a.order=b;a.orderMax=c});!e&&b&&(1<c&&(this.relationList[1].type="d"),Chain.prototype.addPartner.call(this,d));d.addPartner(a,b);return c};
Ties.prototype.delPartner=function(a){var b=this.relationList.indexOf(a);this.relationList.splice(b,1);a.eject()};Ties.prototype.moveUp=function(){if(this.isPrevParent||this.isSibling(this.prevActor)){var a=this.nextSibling;this.ry-=Ties.MOVING_V_STEP;a&&a.prevActor==this&&(a.ry+=Ties.MOVING_V_STEP)}else this.parents.leftSide.ry+=Ties.MOVING_V_STEP};
Ties.prototype.moveDown=function(){if(this.isPrevParent||this.isSibling(this.prevActor)){var a=this.nextSibling;this.ry+=Ties.MOVING_V_STEP;a&&a.prevActor==this&&(a.ry-=Ties.MOVING_V_STEP)}else this.parents.leftSide.ry-=Ties.MOVING_V_STEP};Ties.prototype.moveLeft=function(){this.rx-=2};Ties.prototype.moveRight=function(){this.rx+=2};
Ties.prototype.move=function(){if(!this.prevActor)return!1;var a=this.ax,b=this.ay,c=a-this.x,d=b-this.y,e=Math.abs(c),f=Math.abs(d);if(0==e&&0==f)return!1;e<=Ties.MOVING_STEP?this.x=a:0>c?this.x-=Ties.MOVING_STEP:0<c&&(this.x+=Ties.MOVING_STEP);f<=Ties.MOVING_STEP?this.y=b:0>d?this.y-=Ties.MOVING_STEP:0<d&&(this.y+=Ties.MOVING_STEP);return!0};
$jscomp.global.Object.defineProperties(Ties.prototype,{gender:{configurable:!0,enumerable:!0,get:function(){return this._gender},set:function(a){this._gender=a;this.attributeChanged()}},isMale:{configurable:!0,enumerable:!0,get:function(){return"m"==this.gender}},mother:{configurable:!0,enumerable:!0,get:function(){return this.parents?this.parents.mother:null}},father:{configurable:!0,enumerable:!0,get:function(){return this.parents?this.parents.father:null}},prevSibling:{configurable:!0,enumerable:!0,
get:function(){return this.parents?this.parents.getPrevChild(this):null}},nextSibling:{configurable:!0,enumerable:!0,get:function(){return this.parents?this.parents.getNextChild(this):null}},numOfPartner:{configurable:!0,enumerable:!0,get:function(){return this.relationList.length}},partnerList:{configurable:!0,enumerable:!0,get:function(){var a=this,b=[];this.relationList.forEach(function(c){b.push(c.getPartner(a))});return b}},relationSelected:{configurable:!0,enumerable:!0,get:function(){var a=
!1;this.relationList.forEach(function(b){b.selected&&(a=!0)});return a}},hasBothParents:{configurable:!0,enumerable:!0,get:function(){var a=this.partnerList;if(0==a.length)return!1;a=a[0];return this.parents&&a.parents}},hasChild:{configurable:!0,enumerable:!0,get:function(){var a=!1;this.relationList.forEach(function(b){0<b.children.length&&(a=!0)});return a}},isPrevParent:{configurable:!0,enumerable:!0,get:function(){return null==this.parents?!1:this.prevActor==this.parents.leftSide}}});
Ties.MOVING_V_STEP=2;Ties.MOVING_STEP=.9;var ChainRoot=function(){Chain.call(this);this.id="root";this.radius=5;this.z=-1};$jscomp.inherits(ChainRoot,Chain);ChainRoot.Z=Chain.Z;ChainRoot.prototype.draw=function(a){EditorMain.DEBUG&&(a.save(),a.beginPath(),a.arc(0,0,this.radius,0,2*Math.PI,!1),a.fillStyle="green",a.fill(),a.restore())};$jscomp.global.Object.defineProperties(ChainRoot.prototype,{info:{configurable:!0,enumerable:!0,get:function(){return this.id+"("+this.x+","+this.y+")"}}});
var Controller=function(a){this.init(void 0===a?!1:a);Controller.Instance=this};Controller.prototype.init=function(a){var b=this;this.mouseMoving=this._contextmenu=!1;a||window.addEventListener("contextmenu",function(a){b.mouseMoving||(b._contextmenu=!0);a.preventDefault()});this.initKeys();this.initPointingDevice()};
Controller.prototype.initKeys=function(){var a=this;this.keys={};window.addEventListener("keydown",function(b){b.key?a.keys[b.key]=!0:a.keys["k"+b.keyCode]=!0});window.addEventListener("keyup",function(b){b.key?delete a.keys[b.key]:delete a.keys["k"+b.keyCode]})};
Controller.prototype.initPointingDevice=function(){var a=this,b=document.getElementById("canvas"),c=!1,d=function(){a.point=[];a.prev=[];a.move=[];c=!1};d();b.addEventListener("mousedown",function(b){a.point=[FlexibleView.Instance.convert(b.clientX,b.clientY)];a.prev=a.point;a.move=a.point});b.addEventListener("mousemove",function(b){b=[FlexibleView.Instance.convert(b.clientX,b.clientY)];a.move=b;0<a.prev.length&&(a.point=b);c=!1});b.addEventListener("mouseup",function(){return d()});b.addEventListener("mouseleave",
function(){return d()});b.addEventListener("touchstart",function(b){Array.prototype.forEach.call(b.touches,function(b){a.point.push(FlexibleView.Instance.convert(b.pageX,b.pageY))});a.prev=a.point;a.move=a.point;c=!0;setTimeout(function(){c&&(a._contextmenu=!0)},2E3);b.preventDefault()});b.addEventListener("touchmove",function(b){var d=[];Array.prototype.forEach.call(b.touches,function(a){d.push(FlexibleView.Instance.convert(a.pageX,a.pageY))});a.move=d;0<a.prev.length&&(a.point=d);c=!1});b.addEventListener("touchend",
function(){return d()})};$jscomp.global.Object.defineProperties(Controller.prototype,{delta:{configurable:!0,enumerable:!0,get:function(){var a=this,b=[];this.mouseMoving=!1;this.point.forEach(function(c,d){var e=c.x-a.prev[d].x,f=c.y-a.prev[d].y;b.push({x:e,y:f});a.prev[d]=c;if(0!=e||0!=f)a.mouseMoving=!0});return b}},contextmenu:{configurable:!0,enumerable:!0,get:function(){var a=this._contextmenu;this._contextmenu=!1;return a}}});
var Description=function(a,b,c,d){d=void 0===d?0:d;Actor.call(this,0,0,Chain.Z+1);this.holdable=!0;this.person=a;this.dx=c;this.dy=d;this.text=b};$jscomp.inherits(Description,Actor);Description.prototype.calculate=function(a){var b=Field.Instance.spacing,c=Field.Instance.fontSize,d=0,e=0,f=!0;this.lines.reverse().forEach(function(c){var g=a.measureText(c);d=Math.max(d,g.width/b);f&&0==c.length||(f=!1,e++)});this.width=d;this.height=e*c/b;this.hW=d/2;this.hH=this.height/2};
Description.prototype.isHit=function(a,b){var c=this.y-this.hH,d=this.x+this.hW,e=this.y+this.hH;return this.hit=this.x-this.hW<=a&&a<=d&&c<=b&&b<=e};Description.prototype.drawFrame=function(a){if(this.hit){var b=Field.Instance.spacing,c=-this.hH*b,d=-this.hW*b,e=this.width*b,b=this.height*b;a.lineWidth=3;a.strokeRect(d,c,e,b);a.fillStyle="rgba(127, 255, 255, .1)";a.fillRect(d,c,e,b)}};
Description.prototype.drawLine=function(a){if(this.selected||this.hit){var b=Field.Instance.spacing,c=this.getRadian(this.person),d=-this.x+this.person.x+.5*Math.cos(c),c=-this.y+this.person.y+.5*Math.sin(c);a.beginPath();a.moveTo(d*b,c*b);a.lineTo(0*b,0*b);a.lineWidth=2;a.strokeStyle=Field.Instance.hitStyle;a.stroke()}};
Description.prototype.drawText=function(a){var b=Field.Instance.spacing,c=Field.Instance.fontSize,d=-this.hH*b+c/2,e=-this.hW*b;a.fillStyle="black";this.lines.forEach(function(b){a.fillText(b,e,d);d+=c})};Description.prototype.draw=function(a){this.calculate(a);var b=Field.Instance.spacing,c=this.x*b,b=this.y*b;a.save();a.translate(c,b);this.drawLine(a);this.drawFrame(a);this.drawText(a);a.restore()};
$jscomp.global.Object.defineProperties(Description.prototype,{x:{configurable:!0,enumerable:!0,get:function(){return this.person.x+this.dx},set:function(a){this.person&&(this.dx=a-this.person.x)}},y:{configurable:!0,enumerable:!0,get:function(){return this.person.y+this.dy},set:function(a){this.person&&(this.dy=a-this.person.y)}},lines:{configurable:!0,enumerable:!0,get:function(){return this.text.split(/\r\n|\r|\n/)}}});
var Field=function(a,b){this.width=a;this.height=b;this.view=new FlexibleView(a,b);this.init();Field.Instance=this;EditorMain.DEBUG&&(Field.MAX_GENERATION=99)};Field.prototype.init=function(){this.center=this.ty=this.tx=0;this.targetList=[];this.prevTargetList=[];this.actorList=[];this.dirty=!1;this.maxGeneration=this.minGeneration=0;this.root=new ChainRoot;this.addActor(this.root)};
Field.prototype.clearAll=function(){var a=new Person;this.init();a.principal=!0;this.root.assignActor(a);this.addActor(a);return a};Field.prototype.createPair=function(a,b){var c=null;this.pairList.forEach(function(d){d.isPair(a,b)&&(c=d)});null==c&&(c=new Relation(a,b),this.addActor(c));return c};Field.prototype.getRelationship=function(a,b){var c=null;this.actorList.forEach(function(d){!c&&d instanceof Relationship&&(d.person==a&&d.other==b||d.person==b&&d.other==a)&&(c=d)});return c};
Field.prototype.addTarget=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];var d=this;b.forEach(function(a){(a instanceof Person||a instanceof Relation||a instanceof Relationship||a instanceof EnclosingLine||a instanceof ActorHandle)&&-1==d.targetList.indexOf(a)&&(d.targetList.push(a),2<d.targetList.length&&d.targetList.shift())})};
Field.prototype.addActor=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];var d=this;b.forEach(function(a){-1==d.actorList.indexOf(a)&&(d.actorList.push(a),a instanceof Person&&(d.minGeneration=Math.min(d.minGeneration,a.generation),d.maxGeneration=Math.max(d.maxGeneration,a.generation)))});this.dirty=!0};
Field.prototype.scan=function(a,b){var c=null,d=(a-this.tx)/this.spacing,e=(b-this.ty)/this.spacing;this.actorList.sort(function(a,b){return b.z-a.z});this.actorList.forEach(function(a){a.hit=!1;c||a.isHit(d,e)&&(c=a)});return c};Field.prototype.clearTarget=function(){this.targetList=[]};Field.prototype.clearSelection=function(){this.scan(Number.MAX_VALUE,Number.MAX_VALUE)};
Field.prototype.control=function(){var a=this,b=Controller.Instance,c=b.keys,c=c.Control||c.Shift||c.k16||c.k17,d=b.delta;this.hold||b.move.forEach(function(b){a.scan(b.x,b.y)});b._contextmenu||(0==b.point.length?this.hold=null:c||(this.targetList=[]));b.point.forEach(function(b,c){if(a.hold)b=a.spacing,a.hold.move(d[c].x/b,d[c].y/b);else if(c=a.scan(b.x,b.y))a.addTarget(c),!a.hold&&c.holdable&&(a.hold=c)})};
Field.prototype.arrange=function(){var a=this;if(this.dirty){console.log("*dirty* "+this.actorList.length);this.dirty=!1;var b=0,c=0,d=0,e=0;this.personList.forEach(function(f){var g=f.move(),h=f.x;f=f.y;b=Math.min(b,h);c=Math.min(c,f);d=Math.max(d,h);e=Math.max(e,f);g&&(a.dirty=!0)});this.pairList.forEach(function(b){!a.dirty&&b.reassign()&&(a.dirty=!0)});var f=this.spacing,g=b*f,h=c*f,k=(this.height-(e*f-h))/2;this.tx=(this.width-(d*f-g))/2-g;this.ty=k-h;this.center=b+(d-b)/2}};
Field.prototype.choiceActor=function(){var a=this,b=[].concat(this.actorList);this.actorList=[];b.forEach(function(c){c.isGone||(a.actorList.push(c),c.spawn.forEach(function(c){-1==b.indexOf(c)&&-1==a.actorList.indexOf(c)&&a.addActor(c)}))});this.actorList.length!=b.length&&(this.dirty=!0);this.actorList.sort(function(a,b){return a.z-b.z})};
Field.prototype.drawGrid=function(a){if(this.showGrid){var b=this.width/2,c=this.height/2,d=this.spacing,e=-c,f=-b;a.save();a.lineWidth=.2;a.strokeStyle="aqua";a.translate(b,c);for(var g=0;g<b;g+=d)a.beginPath(),a.moveTo(g,e),a.lineTo(g,c),a.stroke(),0<g&&(a.beginPath(),a.moveTo(-g,e),a.lineTo(-g,c),a.stroke());for(e=0;e<c;e+=d)a.beginPath(),a.moveTo(f,e),a.lineTo(b,e),a.stroke(),0<e&&(a.beginPath(),a.moveTo(f,-e),a.lineTo(b,-e),a.stroke());a.restore()}};
Field.prototype.drawBG=function(a){if(""==document.querySelector('[name="documentId"]').value){a.save();a.font="48px 'Times New Roman'";a.textAlign="center";a.textBaseline="middle";var b=a.measureText("\u30d7\u30ed\u30c8\u30bf\u30a4").width,c=b/2;a.translate(this.tx,this.ty);a.rotate(-Math.PI/4);a.strokeStyle="rgba(222, 222, 222, .2)";for(var d=-this.height;d<this.height;d+=96)for(var e=0==d/48/2%2?0:c,f=-this.width;f<this.width;f+=b)a.strokeText("\u30d7\u30ed\u30c8\u30bf\u30a4",f+e,d);a.restore()}this.drawGrid(a)};
Field.prototype.draw=function(){var a=this,b=this.view.ctx,c=this.fontSize;this.choiceActor();this.view.clear();this.drawBG(b);b.save();b.font=c+"px 'Times New Roman'";b.textBaseline="middle";b.translate(this.tx,this.ty);this.actorList.forEach(function(b){b.selected=-1!=a.targetList.indexOf(b);b.selected&&b instanceof Relationship&&(b.person.selected=!0,b.other.selected=!0)});this.actorList.forEach(function(a){a.fontSize=c;a.draw(b)});b.restore()};
$jscomp.global.Object.defineProperties(Field.prototype,{showGrid:{configurable:!0,enumerable:!0,get:function(){var a=document.querySelector('[name="showGrid"]');return null==a?!0:a.checked}},showName:{configurable:!0,enumerable:!0,get:function(){var a="Top",b=document.querySelectorAll('[name="showName"]');Array.prototype.forEach.call(b,function(b){b.checked&&(a=b.value)});return a}},spacing:{configurable:!0,enumerable:!0,get:function(){var a=document.querySelector('[name="gridSize"]');(a=parseFloat(a.value))||
(a=80);return a}},fontSize:{configurable:!0,enumerable:!0,get:function(){var a=document.querySelector('[name="nameSize"]');(a=parseFloat(a.value))||(a=12);return a}},lineStyle:{configurable:!0,enumerable:!0,get:function(){return"gray"}},hitStyle:{configurable:!0,enumerable:!0,get:function(){return"rgba(100, 255, 255, 0.6)"}},personList:{configurable:!0,enumerable:!0,get:function(){var a=[];this.actorList.forEach(function(b){b instanceof Person&&a.push(b)});return a}},pairList:{configurable:!0,enumerable:!0,
get:function(){var a=[];this.actorList.forEach(function(b){b instanceof Relation&&a.push(b)});return a}},relationshipList:{configurable:!0,enumerable:!0,get:function(){var a=[];this.actorList.forEach(function(b){b instanceof Relationship&&a.push(b)});return a}},shapesList:{configurable:!0,enumerable:!0,get:function(){var a=[];this.actorList.forEach(function(b){b instanceof EnclosingLine&&a.push(b)});return a}},numOfGeneration:{configurable:!0,enumerable:!0,get:function(){return this.maxGeneration-
this.minGeneration+1}},targetChanged:{configurable:!0,enumerable:!0,get:function(){var a=this.targetList.length,b=this.prevTargetList.length,c=a!=b;!c&&0<a&&0<b&&this.targetList[0]!=this.prevTargetList[0]&&(c=!0);this.prevTargetList=this.targetList.slice();return c}}});Field.MAX_GENERATION=5;
var FlexibleView=function(a,b){this.view=document.getElementById("view");this.canvas=document.getElementById("canvas");this.ctx=this.canvas.getContext("2d");this.scale=1;this.init();this.setSize(a,b);FlexibleView.Instance=this};FlexibleView.prototype.setSize=function(a,b){this.width=a;this.height=b;this.canvas.width=a;this.canvas.height=b;this.resize()};
FlexibleView.prototype.init=function(){var a=this,b=document.querySelector('[data-role="header"]'),c=document.querySelector('[data-role="footer"]');this.headerHeight=b?b.offsetHeight:0;this.footerHeight=c?c.offsetHeight:0;this.margin=this.headerHeight+this.footerHeight;window.addEventListener("resize",function(){a.resize()});window.addEventListener("keydown",function(){a.view.classList.contains("addicting")||a.view.classList.add("addicting")});window.addEventListener("mousemove",function(){a.view.classList.remove("addicting")})};
FlexibleView.prototype.resize=function(){var a=document.body.clientWidth/this.width,b=(window.innerHeight-this.margin)/this.height;this.scale=b<a?b:a;this.view.setAttribute("style",["width:"+this.width+"px","height:"+this.height+"px","transform: scale("+this.scale+")"].join(";"))};FlexibleView.prototype.convert=function(a,b){return{x:a/this.scale,y:(b-this.headerHeight)/this.scale}};FlexibleView.prototype.clear=function(){this.ctx.clearRect(0,0,this.width,this.height)};
var GenoCalendar=function(a){this.day=this.month=this.year=null;a&&this.setupDate(new String(a))};GenoCalendar.prototype.setupDate=function(a){var b=a.split(/[-/]/g);a=(new Date).getFullYear()+1;var c=parseInt(b[0]);Number.isFinite(c)?c+1900<a&&(c+=1900):c=null;this.year=c;if(1<b.length){a=parseInt(b[1]);if(2<b.length)b=new Date(c,a-1,parseInt(b[2])),b.getFullYear(),a=b.getMonth()+1,this.day=b=b.getDate();else if(0>a||12<a)a=1;this.month=a}};
GenoCalendar.prototype.toString=function(){var a=[];this.year&&(a.push(this.year),this.month&&(a.push(this.month),this.day&&a.push(this.day)));return a.join("-")};
$jscomp.global.Object.defineProperties(GenoCalendar.prototype,{age:{configurable:!0,enumerable:!0,get:function(){if(!this.year)return null;var a=new Date,b=a.getFullYear();if(!this.month)return b-this.year;var c=a.getMonth()+1;if(!this.dd)return Math.floor((100*b+c-(100*this.year+this.month))/100);a=a.getDate();return Math.floor((1E4*b+100*c+a-(1E4*this.year+100*this.month+this.day))/1E4)}}});
var Occupancy=function(a,b,c,d,e){a=void 0===a?null:a;b=void 0===b?Number.MAX_SAFE_INTEGER:b;c=void 0===c?Number.MAX_SAFE_INTEGER:c;d=void 0===d?Number.MIN_SAFE_INTEGER:d;e=void 0===e?Number.MIN_SAFE_INTEGER:e;this.top=b;this.left=c;this.right=d;this.bottom=e;this.personList=[];a&&(this.right=this.left=b=a.ax,this.personList.push(a))};Occupancy.prototype.isDone=function(a){return-1!=this.personList.indexOf(a)};
Occupancy.prototype.merge=function(a){this.top=Math.min(this.top,a.top);this.left=Math.min(this.left,a.left);this.right=Math.max(this.right,a.right);this.bottom=Math.max(this.bottom,a.bottom);this.personList=this.personList.concat(a.personList)};$jscomp.global.Object.defineProperties(Occupancy.prototype,{width:{configurable:!0,enumerable:!0,get:function(){return this.right-this.left}}});
var Person=function(a){Ties.call(this,void 0===a?"u":a);this.seq=Tally.increment();this.name=EditorMain.DEBUG?AlphabeticalTally.increment():"";this._description=null;this._dod=this._dob="";this.death=!1;this.abuse=this.illness=0;this.attr="";this.principal=!1};$jscomp.inherits(Person,Ties);Person.Z=Ties.Z;Person.MOVING_STEP=Ties.MOVING_STEP;Person.MOVING_V_STEP=Ties.MOVING_V_STEP;
Person.prototype.attributeChanged=function(){var a=this.age;this.symbol=null!=a&&0>a?this.dod?new MiscarriageSymbol(this):new FetusSymbol(this):this.isMale?new MaleSymbol(this):new FemaleSymbol(this);this.death=this.dod&&0<this.dod.length};Person.prototype.touch=function(a){var b=this.x-a.x;a=this.y-a.y;1>=Math.sqrt(b*b+a*a)&&(this.touched=!0);return this.touched};Person.prototype.isHit=function(a,b){return this.hit=this.symbol.isHit(a,b)};
Person.prototype.remove=function(){Ties.prototype.eject.call(this);this.description=null;this.parents&&this.parents.removeChild(this);if(1==this.numOfPartner){var a=this.partnerList[0];a.delPartner(this.relationList[0]);this.parents||a.parents||a.principal||a.remove()}};
Person.prototype.drawSymbol=function(a){this.selected||this.relationSelected?(this.strokeStyle="#4178be",a.lineWidth=5):(this.strokeStyle="black",a.lineWidth=3);this.touched&&(this.strokeStyle="red");this.symbol.draw(a);this.hit&&(this.strokeStyle=Field.Instance.hitStyle,a.lineWidth=7,this.symbol.draw(a))};
Person.prototype.drawAncestorOccupancy=function(a){if(this.parents){var b=Field.Instance.spacing,c=this.ancestorOccupancy(),d=c.left-1,c=c.right+1,e=(this.y-.1)*b;a.strokeStyle="purple";a.beginPath();a.moveTo(d*b,e);a.lineTo(c*b,e);a.stroke()}};Person.prototype.drawDescendantOccupancy=function(a){var b=Field.Instance.spacing,c=this.getOccupancy(),d=c.left-1,c=c.right+1,e=(this.y+.1)*b;a.lineWidth=3;a.strokeStyle="green";a.beginPath();a.moveTo(d*b,e);a.lineTo(c*b,e);a.stroke()};
Person.prototype.drawOccupancy=function(a){if(EditorMain.DEBUG){var b=Controller.Instance.keys;if(this.hit||b.Control)this.drawAncestorOccupancy(a),this.drawDescendantOccupancy(a)}};
Person.prototype.drawChain=function(a){if(this.prevActor&&EditorMain.DEBUG){var b=Controller.Instance.keys;if(this.hit||b.Control){var b=Field.Instance.spacing,c=this.prevActor,d=this.isPartner(c),e=c.x-this.x,c=c.y-this.y,f=0,g=0;0>e?(c-=.2,f-=.1*b,g-=.2*b):(c+=.2,f+=.1*b,g+=.2*b);e*=b;c*=b;a.lineWidth=.6;a.strokeStyle="lime";a.beginPath();a.arc(e,c,4,0,2*Math.PI,!1);a.moveTo(e,c);d?a.quadraticCurveTo(e+(f-e)/2,c+.5*b*(this.isMale?1:-1),f,g):a.lineTo(f,g);a.stroke()}}};
Person.prototype.draw=function(a){var b=Field.Instance.spacing,c=this.x*b,b=this.y*b;a.save();this.drawOccupancy(a);a.translate(c,b);this.drawChain(a);this.drawSymbol(a);a.restore()};Person.prototype.appendTo=function(a,b){var c=this;Person.Properties.forEach(function(d){var e=c[d];e&&a.append(b+d,e)})};Person.createFromEntity=function(a){var b=new Person;Person.Properties.forEach(function(c){var d=a[c];d&&(b[c]=d)});return b};
$jscomp.global.Object.defineProperties(Person.prototype,{description:{configurable:!0,enumerable:!0,get:function(){return null==this._description?"":this._description.text},set:function(a){null==a||0==a.length?null!=this._description&&(this._description.eject(),this._description=null):null!=this._description?this._description.text=a:(this._description=new Description(this,a,1),this.spawnList.push(this._description))}},dx:{configurable:!0,enumerable:!0,get:function(){return null==this._description?
0:this._description.dx},set:function(a){null!=this._description&&(this._description.dx=a)}},dy:{configurable:!0,enumerable:!0,get:function(){return null==this._description?0:this._description.dy},set:function(a){null!=this._description&&(this._description.dy=a)}},dob:{configurable:!0,enumerable:!0,get:function(){return this._dob},set:function(a){this._dob=a;this.attributeChanged()}},dod:{configurable:!0,enumerable:!0,get:function(){return this._dod},set:function(a){this._dod=a;this.attributeChanged()}},
age:{configurable:!0,enumerable:!0,get:function(){return(new GenoCalendar(this.dob)).age}},info:{configurable:!0,enumerable:!0,get:function(){var a=this.name,b=this.age;b&&(a+="("+b+")");return a}},radius:{configurable:!0,enumerable:!0,get:function(){return Field.Instance.spacing/2}},removable:{configurable:!0,enumerable:!0,get:function(){if(this.principal)return!1;var a=this.numOfPartner;if(0==a)return!0;if(1==a){if(!this.parents&&!this.hasChild)return!0;var a=this.partnerList[0],b=this.relationList[0].children.length;
if(!this.parents&&!a.parents&&1==b)return!0}return!1}}});Person.MarriageableAge=10;Person.Properties="id seq name description dx dy gender dob dod death illness abuse attr bornOrder generation prevId rx ry".split(" ");var Relation=function(a,b){Actor.call(this);a.isMale?(this.leftSide=a,this.rightSide=b):(this.leftSide=b,this.rightSide=a);this.type="m";this.children=[];this.hit=!1;this.initImage()};$jscomp.inherits(Relation,Actor);
Relation.prototype.initImage=function(){var a=this;this.divorceImage=new Image;this.divorceImage.src="img/relation.divorce.png";this.separateImage=new Image;this.separateImage.src="img/relation.separate.png";this.dottedImage=new Image;this.dottedImage.src="img/relation.dotted.png";this.dottedImage.onload=function(){a.dottedStyle=FlexibleView.Instance.ctx.createPattern(a.dottedImage,"repeat")}};
Relation.prototype.isPair=function(a,b){return this.leftSide==a&&this.rightSide==b||this.leftSide==b&&this.rightSide==a?!0:!1};Relation.prototype.getPartner=function(a){return a==this.father?this.mother:this.father};
Relation.prototype.addChild=function(a,b){b=void 0===b?!0:b;console.log("Relation#addChild:"+a.info);a.parents=this;this.children.push(a);this.reserve(a);if(b)if(a.prevActor)a.assignActor(this.father,-1,-2),this.mother.generation=this.father.generation;else{var c=1;if(b=a.prevSibling)var c=b.ax-this.father.ax,d=b.descendantOccupancy(),c=c+d.right-b.ax+2;this.father.assignActor(a,c,2)}};Relation.prototype.getPrevChild=function(a){a=this.children.indexOf(a);return 1>a?null:this.children[a-1]};
Relation.prototype.getNextChild=function(a){a=this.children.indexOf(a)+1;return this.children.length<=a?null:this.children[a]};Relation.prototype.reorder=function(){this.children.forEach(function(a,b){a.bornOrder=b+1})};Relation.prototype.narrowly=function(){this.leftSide.separate(this.rightSide,-1)};Relation.prototype.widely=function(){this.leftSide.separate(this.rightSide,1)};
Relation.prototype.reassignOccupancy=function(){if(!(this.father.parents&&this.mother.parents&&this.leftSide.rest&&this.rightSide.rest))return!1;console.log("Relation#reassignOccupancy");var a=this.leftSide.ancestorOccupancy(new Occupancy(this.leftSide)),b=this.rightSide.ancestorOccupancy(new Occupancy(this.rightSide)),c=a.right-b.left+2;return 0!=c?(console.log("desired:"+c+"/"+a.right+"|"+b.left),this.leftSide.separate(this.rightSide,c),!0):!1};
Relation.prototype.reassignChildren=function(){var a=this,b=!1;if(0==this.children.length)return b;var c=this.rect,d=null,e=0,f=[0],g=0;this.children.forEach(function(b,c){var h=b.getOccupancy(),k=b.ax-h.left+1;if(b==a.leftSide.prevActor||b==a.rightSide.prevActor)d=b;0<c&&(e+=g+k,f.push(e));g=h.right-b.ax+1});if(null==d){var h=c.center-e/2;this.children.forEach(function(a,c){a.reassignAbsolute(h+f[c])&&(b=!0)});return b}var k=this.children.indexOf(d),l=d.ax-f[k];this.leftSide.reassignAbsolute(l+e/
2-(c.center-c.left))&&(b=!0);this.children.forEach(function(a,c){a.reassignAbsolute(l+f[c])&&(b=!0)});return b};Relation.prototype.reassign=function(){return this.reassignChildren()};Relation.prototype.removeChild=function(a){var b=this.children.indexOf(a);this.children.splice(b,1);a.eject()};Relation.prototype.isHit=function(a,b){var c=this.rect;this.hit=!1;c.left<=a&&a<=c.right&&c.top<=b&&b<=c.bottom&&(this.hit=!0);return this.hit};
Relation.prototype.eject=function(){Actor.prototype.eject.call(this);this.children.forEach(function(a){a.parents=null})};Relation.prototype.drawOccupancy=function(a){var b=this.occupancy;if(0!=b.left){var c=Field.Instance.spacing,d=c/2,e=this.rect,f=e.center-b.left*d,e=e.bottom,b=(b.left+b.right)*d;a.strokeStyle="green";a.strokeRect(f,e,b,c)}};
Relation.prototype.drawNormal=function(a){var b=Field.Instance.spacing,c=this.rect,d=c.top*b,e=c.left*b,f=c.right*b,g=c.bottom*b,b=c.center*b;a.save();a.beginPath();a.moveTo(e,d);a.lineTo(e,g);a.lineTo(f,g);a.lineTo(f,d);a.stroke();a.translate(-8,-8);"d"==this.type?a.drawImage(this.divorceImage,b,g):"s"==this.type&&a.drawImage(this.separateImage,b,g);a.restore()};
Relation.prototype.drawText=function(a){var b=Field.Instance.spacing;a.fillText(this.fatherOrder+"/"+this.motherOrder,this.rect.center*b,this.top*b)};
Relation.prototype.drawChildLine=function(a){if(0!=this.children.length){var b=Field.Instance.spacing,c=(this.y+.25)*b,d=!0,e=null,f=this.rect,g=f.center*b,f=f.bottom*b;a.strokeStyle=Field.Instance.lineStyle;a.beginPath();a.moveTo(g,f);a.lineTo(g,c);this.children.forEach(function(f){var g=f.x*b,h=(f.y-.5)*b;d&&(a.lineTo(g,c),a.stroke(),d=!1);a.beginPath();a.moveTo(g,c);a.lineTo(g,h);a.stroke();e=f});a.beginPath();a.moveTo(g,c);a.lineTo(e.x*b,c);a.stroke()}};
Relation.prototype.draw=function(a,b){a.save();a.lineWidth=2;this.drawChildLine(a);a.strokeStyle="c"==this.type?this.dottedStyle:Field.Instance.lineStyle;this.drawNormal(a);if(this.hit||this.selected)a.lineWidth=6,a.strokeStyle=Field.Instance.hitStyle,this.drawNormal(a),EditorMain.DEBUG&&this.drawText(a);a.restore()};Relation.prototype.createEntity=function(){return{id:this.id}};
$jscomp.global.Object.defineProperties(Relation.prototype,{father:{configurable:!0,enumerable:!0,get:function(){return this.leftSide.isMale?this.leftSide:this.rightSide}},mother:{configurable:!0,enumerable:!0,get:function(){return this.leftSide.isMale?this.rightSide:this.leftSide}},info:{configurable:!0,enumerable:!0,get:function(){return this.leftSide.info+"_"+this.rightSide.info}},x:{configurable:!0,enumerable:!0,get:function(){return this.left+Math.abs(this.leftSide.x-this.rightSide.x)/2}},y:{configurable:!0,
enumerable:!0,get:function(){return this.leftSide.y+1}},top:{configurable:!0,enumerable:!0,get:function(){return this.leftSide.y+.5}},left:{configurable:!0,enumerable:!0,get:function(){return Math.min(this.leftSide.x,this.rightSide.x)}},partnerOrder:{configurable:!0,enumerable:!0,get:function(){return Math.max(this.father.partnerOrder,this.mother.partnerOrder)}},fatherOrder:{configurable:!0,enumerable:!0,get:function(){return this.mother.getOrder(this.father)}},motherOrder:{configurable:!0,enumerable:!0,
get:function(){return this.father.getOrder(this.mother)}},order:{configurable:!0,enumerable:!0,get:function(){return this.relationOrder},set:function(a){this.z=Chain.Z-a;this.relationOrder=a}},firstChild:{configurable:!0,enumerable:!0,get:function(){return this.children[0]}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.children[this.children.length-1]}},rect:{configurable:!0,enumerable:!0,get:function(){var a=this.father,b=this.mother,c=a.y+.5,d=Math.min(a.x,b.x),e=Math.abs(a.x-
b.x),f=.25+.1*(this.order-1);this.x=a=1==this.father.numOfPartner&&1==this.mother.numOfPartner?this.father.x+(this.mother.x-this.father.x)/2:this.fatherOrder<this.motherOrder?b.x-1:a.x+1;this.y=c+f;return{top:c,left:d,right:d+e,bottom:c+f,center:a,width:e,height:f}}},allChildren:{configurable:!0,enumerable:!0,get:function(){var a=[];this.children.forEach(function(b){var c=b.partnerList;b.isMale?(a.push(b),a=a.concat(c)):(a=a.concat(c),a.push(b))});return a}},occupancy:{configurable:!0,enumerable:!0,
get:function(){var a=this.allChildren.length;if(1==this.children.length){var b=2*a-1;this.children[0].isMale?a=1:(a=b,b=1)}else b=a;return{left:a,right:b}}}});var GenoSymbol=function(a){this.person=a};GenoSymbol.prototype.drawIllness=function(a){};GenoSymbol.prototype.drawAbuse=function(a){};GenoSymbol.prototype.drawSymbol=function(a){var b=this.width;a.strokeRect(-this.radius,-this.radius,b,b);if(this.person.principal){var b=this.ir,c=2*b;a.strokeRect(-b,-b,c,c)}};
GenoSymbol.prototype.drawCross=function(a){};GenoSymbol.prototype.drawYears=function(a){new GenoCalendar(this.person.dob);var b=new GenoCalendar(null);var c=new GenoCalendar(this.person.dod);b=[b.year,c.year].join("-");1>=b.length||(c=-this.radius,a.save(),a.textBaseline="bottom",a.fillText(b,0,c),a.restore())};GenoSymbol.prototype.drawAge=function(a){var b=this.person.age;null==b||0>b||(a.strokeText(b,0,0),a.fillText(b,0,0))};
GenoSymbol.prototype.drawName=function(a){var b=Field.Instance.showName;if("Off"!=b){var c=this.person.name,d=0;a.save();"Top"==b?(d=.8*-this.radius,a.textBaseline="top"):"Middle"==b?(d=.8*this.radius,a.textBaseline="bottom"):"Bottom"==b&&(a.textBaseline="top",d=1.1*this.radius);EditorMain.DEBUG&&(c="#"+this.person.generation+":"+c);a.lineWidth=3;a.strokeStyle="rgba(220, 220, 220, .8)";a.strokeText(c,1,d+1);a.fillText(c,0,d);a.restore()}};
GenoSymbol.prototype.drawAttr=function(a){var b=Field.Instance.showName,c=this.person.attr;a.save();"Middle"==b?(b=.8*-this.radius,a.textBaseline="top"):(b=.8*this.radius,a.textBaseline="bottom");a.fillText(c,0,b);a.restore()};GenoSymbol.prototype.resetProperties=function(){this.radius=this.person.radius;this.width=2*this.radius;this.ir=.85*this.radius;this.fontSize=this.person.fontSize;this.textMargin=.2*this.fontSize;this.textHh=this.fontSize/2+this.textMargin};
GenoSymbol.prototype.draw=function(a){this.resetProperties();a.save();this.drawIllness(a);this.drawAbuse(a);a.strokeStyle=this.person.strokeStyle;this.drawSymbol(a);this.person.death&&(a.lineWidth=.5,this.drawCross(a));a.textAlign="center";a.lineWidth=1;a.strokeStyle="black";a.fillStyle="black";this.drawAge(a);this.drawYears(a);this.drawName(a);this.drawAttr(a);a.restore()};GenoSymbol.ColorIllness="rgba(200, 200, 200, .6)";GenoSymbol.ColorAbuse="rgba(200, 200, 200, .6)";
var FemaleSymbol=function(a){GenoSymbol.apply(this,arguments)};$jscomp.inherits(FemaleSymbol,GenoSymbol);FemaleSymbol.ColorAbuse=GenoSymbol.ColorAbuse;FemaleSymbol.ColorIllness=GenoSymbol.ColorIllness;FemaleSymbol.prototype.isHit=function(a,b){var c=this.person;a=c.x-a;b=c.y-b;return.5>=Math.sqrt(a*a+b*b)};FemaleSymbol.prototype.drawIllness=function(a){if(this.person.illness){var b=Math.PI/2;a.save();a.beginPath();a.arc(0,0,this.radius,b,-b,!1);a.fillStyle=GenoSymbol.ColorIllness;a.fill();a.restore()}};
FemaleSymbol.prototype.drawAbuse=function(a){this.person.abuse&&(a.save(),a.beginPath(),a.arc(0,0,this.radius,0,-Math.PI,!1),a.fillStyle=GenoSymbol.ColorAbuse,a.fill(),a.restore())};FemaleSymbol.prototype.drawSymbol=function(a){a.beginPath();a.arc(0,0,this.radius,0,2*Math.PI,!1);a.stroke();this.person.principal&&(a.beginPath(),a.arc(0,0,this.ir,0,2*Math.PI,!1),a.stroke())};
FemaleSymbol.prototype.drawCross=function(a){var b=Math.PI/2,c=b/2,d=Math.cos(c+b)*this.radius,b=-Math.sin(c+b)*this.radius,e=Math.sin(c)*this.radius,c=Math.cos(-c)*this.radius;a.beginPath();a.moveTo(b,d);a.lineTo(e,c);a.stroke();a.beginPath();a.moveTo(e,d);a.lineTo(b,c);a.stroke()};var FetusSymbol=function(a){GenoSymbol.apply(this,arguments)};$jscomp.inherits(FetusSymbol,GenoSymbol);FetusSymbol.ColorAbuse=GenoSymbol.ColorAbuse;FetusSymbol.ColorIllness=GenoSymbol.ColorIllness;
FetusSymbol.prototype.isHit=function(a,b){var c=this.person;b=c.y-b;return.5>=Math.abs(c.x-a)&&.5>=Math.abs(b)};FetusSymbol.prototype.drawIllness=function(a){this.person.illness&&(a.save(),a.beginPath(),a.moveTo(0,-this.radius),a.lineTo(-this.radius,this.radius),a.lineTo(0,this.radius),a.lineTo(0,-this.radius),a.fillStyle=GenoSymbol.ColorIllness,a.fill(),a.restore())};
FetusSymbol.prototype.drawAbuse=function(a){if(this.person.abuse){var b=Math.sqrt(this.width*this.width/2),c=b-this.radius,b=-b/2,d=-b;a.save();a.beginPath();a.moveTo(d,c);a.lineTo(b,c);a.lineTo(-this.radius,this.radius);a.lineTo(this.radius,this.radius);a.lineTo(d,c);a.fillStyle=GenoSymbol.ColorAbuse;a.fill();a.restore()}};
FetusSymbol.prototype.drawSymbol=function(a){a.beginPath();a.moveTo(0,-this.radius);a.lineTo(-this.radius,this.radius);a.lineTo(this.radius,this.radius);a.lineTo(0,-this.radius);a.stroke()};FetusSymbol.prototype.drawCross=function(a){var b=-this.radius/2,c=this.radius/2;a.beginPath();a.moveTo(b,0);a.lineTo(this.radius,this.radius);a.stroke();a.beginPath();a.moveTo(c,0);a.lineTo(-this.radius,this.radius);a.stroke()};var MaleSymbol=function(a){GenoSymbol.apply(this,arguments)};
$jscomp.inherits(MaleSymbol,GenoSymbol);MaleSymbol.ColorAbuse=GenoSymbol.ColorAbuse;MaleSymbol.ColorIllness=GenoSymbol.ColorIllness;MaleSymbol.prototype.isHit=function(a,b){var c=this.person;b=c.y-b;return.5>=Math.abs(c.x-a)&&.5>=Math.abs(b)};MaleSymbol.prototype.drawIllness=function(a){if(this.person.illness){var b=-this.radius,c=-this.radius;a.save();a.fillStyle=GenoSymbol.ColorIllness;a.fillRect(b,c,this.radius,this.width);a.restore()}};
MaleSymbol.prototype.drawAbuse=function(a){if(this.person.abuse){var b=-this.radius;a.save();a.fillStyle=GenoSymbol.ColorAbuse;a.fillRect(b,0,this.width,this.radius);a.restore()}};MaleSymbol.prototype.drawCross=function(a){var b=-this.radius,c=-this.radius,d=this.radius,e=this.radius;a.beginPath();a.moveTo(c,b);a.lineTo(d,e);a.stroke();a.beginPath();a.moveTo(d,b);a.lineTo(c,e);a.stroke()};var MiscarriageSymbol=function(a){GenoSymbol.apply(this,arguments)};$jscomp.inherits(MiscarriageSymbol,GenoSymbol);
MiscarriageSymbol.ColorAbuse=GenoSymbol.ColorAbuse;MiscarriageSymbol.ColorIllness=GenoSymbol.ColorIllness;MiscarriageSymbol.prototype.isHit=function(a,b){var c=this.person;a=c.x-a;b=c.y-.25-b;return.25>=Math.sqrt(a*a+b*b)};MiscarriageSymbol.prototype.drawSymbol=function(a){var b=this.radius/2;a.beginPath();a.arc(0,-b,b,0,2*Math.PI,!1);a.stroke();a.arc(0,-b,b,0,2*Math.PI,!1);a.fill()};var Relationship=function(a,b){Actor.call(this,0,0,Chain.Z+2);this.person=a;this.other=b;this.createFillStyle()};
$jscomp.inherits(Relationship,Actor);Relationship.prototype.createFillStyle=function(a,b){a=void 0===a?null:a;b=void 0===b?"repeat-x":b;var c=this,d=Field.Instance.spacing,e=FlexibleView.Instance.ctx;this.height=16/d;this.fillStyle="rgba(200, 200, 255, 0.7)";this.img=new Image;this.img.onload=function(){c.height=c.img.height/d;c.fillStyle=e.createPattern(c.img,b)};a&&(this.img.src=a)};
Relationship.prototype.calculatePosition=function(){if(this.person.isGone||this.other.isGone)this.eject();else{this.bx=this.person.x;this.by=this.person.y;this.ex=this.other.x;this.ey=this.other.y;var a=this.ex-this.bx,b=this.ey-this.by;this.cx=this.bx+a/2;this.cy=this.by+b/2;this.radian=Math.atan2(b,a);this.length=Math.sqrt(a*a+b*b);this.width=this.length-1.1;this.left=-this.width/2;this.right=this.width/2}};
Relationship.prototype.flip=function(){var a=this.person;this.person=this.other;this.other=a};Relationship.prototype.isHit=function(a,b){a=this.cx-a;var c=this.cy-b,d=-this.radian;b=Math.cos(d)*a-Math.sin(d)*c;a=Math.sin(d)*a+Math.cos(d)*c;var c=this.height,d=-c/2,e=this.left,f=this.width+e;return this.hit=e<=b&&b<=f&&d<=a&&a<=d+c};
Relationship.prototype.drawAuxiliary=function(a){var b=Field.Instance.spacing,c=this.bx*b,d=this.by*b,e=this.ex*b,f=this.ey*b,g=this.cx*b,b=this.cy*b;a.save();a.strokeStyle="blue";a.beginPath();a.moveTo(c,d);a.lineTo(e,f);a.stroke();a.fillStyle="red";a.beginPath();a.arc(c,d,4,0,2*Math.PI,!1);a.fill();a.beginPath();a.arc(e,f,4,0,2*Math.PI,!1);a.fill();a.beginPath();a.arc(g,b,4,0,2*Math.PI,!1);a.fill();a.restore()};
Relationship.prototype.drawTriangle=function(a){var b=Field.Instance.spacing,c=this.cx*b,d=this.cy*b,b=this.width/2*b;a.save();a.translate(c,d);a.rotate(this.radian);a.translate(b,0);a.beginPath();a.moveTo(0,0);a.lineTo(-16,-8);a.lineTo(-16,8);a.lineTo(0,0);a.fill();a.restore()};Relationship.prototype.drawLine=function(a,b,c){var d=this.left*Field.Instance.spacing,e=-c/2;a.save();a.translate(d,e);a.fillStyle=this.fillStyle;a.fillRect(0,0,b,c);a.restore()};
Relationship.prototype.drawRect=function(a,b,c){var d=this.left*Field.Instance.spacing,e=-c/2;a.save();a.translate(d,e);a.fillRect(0,0,b,c);a.restore()};
Relationship.prototype.draw=function(a){this.calculatePosition();var b=Field.Instance.spacing,c=this.width*b,d=this.height*b+1,e=this.cx*b,b=this.cy*b;a.save();a.translate(e,b);a.rotate(this.radian);a.fillStyle="rgba(255, 255, 255, 0.5)";this.drawRect(a,c,d/2);this.drawLine(a,c,d);this.hit&&(a.fillStyle=Field.Instance.hitStyle,this.drawRect(a,c,d));a.restore()};
Relationship.create=function(a,b,c){b="Fused"==a?new FusedRelation(b,c):"Close"==a?new CloseRelation(b,c):"Distant"==a?new DistantRelation(b,c):"Hostile"==a?new HostileRelation(b,c):"FusedHostile"==a?new FusedHostileRelation(b,c):"CloseHostile"==a?new CloseHostileRelation(b,c):"CutOff"==a?new CutOffRelation(b,c):"Focused"==a?new FocusedRelation(b,c):"SexualAbuse"==a?new SexualAbuseRelation(b,c):"PhysicalAbuse"==a?new PhysicalAbuseRelation(b,c):new Relationship(b,c);b.emotion=a;return b};
var CloseHostileRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.closeHostile.png")};$jscomp.inherits(CloseHostileRelation,Relationship);CloseHostileRelation.create=Relationship.create;var CloseRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.close.png")};$jscomp.inherits(CloseRelation,Relationship);CloseRelation.create=Relationship.create;
var CutOffRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.cutOff.png","no-repeat")};$jscomp.inherits(CutOffRelation,Relationship);CutOffRelation.create=Relationship.create;
CutOffRelation.prototype.drawLine=function(a,b,c){var d=Field.Instance.spacing,e=c/2,f=this.left*d,d=this.right*d;a.save();a.translate(-e,-e);a.fillStyle=this.fillStyle;a.fillRect(0,0,b,c);a.restore();a.beginPath();a.moveTo(f,0);a.lineTo(.8*-e,0);a.stroke();a.beginPath();a.moveTo(d,0);a.lineTo(.8*e,0);a.stroke()};var DistantRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.distant.png")};$jscomp.inherits(DistantRelation,Relationship);DistantRelation.create=Relationship.create;
var FocusedRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.focused.png")};$jscomp.inherits(FocusedRelation,Relationship);FocusedRelation.create=Relationship.create;FocusedRelation.prototype.draw=function(a){Relationship.prototype.draw.call(this,a);this.drawTriangle(a)};var FusedHostileRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.fusedHostile.png")};$jscomp.inherits(FusedHostileRelation,Relationship);
FusedHostileRelation.create=Relationship.create;var FusedRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.fused.png")};$jscomp.inherits(FusedRelation,Relationship);FusedRelation.create=Relationship.create;var HostileRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.hostile.png")};$jscomp.inherits(HostileRelation,Relationship);HostileRelation.create=Relationship.create;
var PhysicalAbuseRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.hostile.png")};$jscomp.inherits(PhysicalAbuseRelation,Relationship);PhysicalAbuseRelation.create=Relationship.create;PhysicalAbuseRelation.prototype.draw=function(a){Relationship.prototype.draw.call(this,a);this.drawTriangle(a)};var SexualAbuseRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.hostile.png")};$jscomp.inherits(SexualAbuseRelation,Relationship);
SexualAbuseRelation.create=Relationship.create;SexualAbuseRelation.prototype.draw=function(a){Relationship.prototype.draw.call(this,a);this.drawTriangle(a)};var ActorHandle=function(a,b,c){Actor.call(this,a,b,c);this.type="EnclosureHandle";this.holdable=!0;this.radius=.15;this.logicalRadius=2*this.radius;this.prev=this;this.next=this;this.initImage()};$jscomp.inherits(ActorHandle,Actor);
ActorHandle.prototype.initImage=function(){var a=this,b=FlexibleView.Instance.ctx;"function"!==typeof b.setLineDash&&(this.dottedImage=new Image,this.dottedImage.src="img/relation.dotted.png",this.dottedImage.onload=function(){a.dottedStyle=b.createPattern(a.dottedImage,"repeat")})};ActorHandle.prototype.add=function(a){var b=this.next;this.next=a;a.prev=this;a.next=b;b.prev=a};ActorHandle.prototype.isHit=function(a,b){return this.parent.selected?this.hit=this.includes(a,b,this.logicalRadius):!1};
ActorHandle.prototype.isLineHit=function(a,b){if(this.includes(a,b,this.logicalRadius))return!1;for(var c=!1,d=this.nextCp,e=this.next.prevCp,f=this.getDistance(this.next)/this.radius,g=0;g<f;g++){var h=this.getInterimPoint(d,g,f),k=e.getInterimPoint(this.next,g,f),l=d.getInterimPoint(e,g,f),h=h.getInterimPoint(l,g,f),k=l.getInterimPoint(k,g,f),l=h.getInterimPoint(k,g,f),k=l.x-a,l=l.y-b;Math.sqrt(k*k+l*l)<this.radius&&(c=!0)}return c};
ActorHandle.prototype.increase=function(){var a=new ActorHandle(this.x+.1,this.y+.1,this.z);a.parent=this.parent;this.add(a);this.reserve(a)};ActorHandle.prototype.eject=function(){Actor.prototype.eject.call(this);var a=this.prev,b=this.next;a.next=b;b.prev=a};ActorHandle.prototype.move=function(a,b){Actor.prototype.move.call(this,a,b);Field.Instance.addTarget(this.parent)};
ActorHandle.prototype.drawGuide=function(a){var b=Field.Instance.spacing,c=this.x*b,d=this.y*b,e=this.prevCp,f=this.nextCp,g=e.x*b,e=e.y*b,h=f.x*b,b=f.y*b;a.save();a.lineWidth=1;a.strokeStyle="cyan";a.beginPath();a.moveTo(c,d);a.lineTo(g,e);a.stroke();a.strokeStyle="lime";a.beginPath();a.moveTo(c,d);a.lineTo(h,b);a.stroke();a.restore()};
ActorHandle.prototype.drawSelfCurve=function(a){var b=Field.Instance.spacing,c=this.nextCp,d=this.next.prevCp,e=this.getDistance(this.next)/this.radius,f=this.radius*b;a.save();for(var g=0;g<e;g++){var h=this.getInterimPoint(c,g,e),k=d.getInterimPoint(this.next,g,e),l=c.getInterimPoint(d,g,e),h=h.getInterimPoint(l,g,e),k=l.getInterimPoint(k,g,e),l=h.getInterimPoint(k,g,e),k=l.x*b,l=l.y*b;a.strokeStyle="pink";a.beginPath();a.arc(k,l,f,0,2*Math.PI,!1);a.stroke()}a.restore()};
ActorHandle.prototype.drawSimpleCurve=function(a){var b=Field.Instance.spacing,c=this.x*b,d=this.y*b,e=this.next.x*b,f=this.next.y*b,g=this.nextCp,h=this.next.prevCp,k=g.x*b,g=g.y*b,l=h.x*b,b=h.y*b;a.beginPath();a.moveTo(c,d);a.bezierCurveTo(k,g,l,b,e,f);a.stroke()};
ActorHandle.prototype.drawCurve=function(a){a.save();"Dotted"==this.lineStyle&&("function"===typeof a.setLineDash?a.setLineDash([4]):a.strokeStyle=this.dottedStyle);a.lineWidth=.8;this.drawSimpleCurve(a);this.parent.selected?(a.lineWidth=3,a.strokeStyle="#4178be",this.drawSimpleCurve(a)):this.parent.hit&&(a.lineWidth=3,a.strokeStyle=Field.Instance.hitStyle,this.drawSimpleCurve(a));a.restore();EditorMain.DEBUG&&this.drawSelfCurve(a)};
ActorHandle.prototype.drawArc=function(a){var b=Field.Instance.spacing,c=this.x*b,d=this.y*b;a.save();a.beginPath();a.fillStyle=this.hit?"aqua":"gray";a.arc(c,d,this.radius*b,0,2*Math.PI,!1);a.fill();a.restore()};ActorHandle.prototype.draw=function(a){this.drawCurve(a);this.parent.selected&&(this.drawArc(a),this.next.drawArc(a))};
$jscomp.global.Object.defineProperties(ActorHandle.prototype,{isRoot:{configurable:!0,enumerable:!0,get:function(){return this.parent.root==this}},regId:{configurable:!0,enumerable:!0,get:function(){return this.isRoot?this.parent.id:this.id}},parentId:{configurable:!0,enumerable:!0,get:function(){return this.isRoot?null:this.parent.id}},lineStyle:{configurable:!0,enumerable:!0,get:function(){return this.parent.lineStyle}},list:{configurable:!0,enumerable:!0,get:function(){for(var a=[],b=this.next;b!=
this;)a.push(b),b=b.next;return a}},listAll:{configurable:!0,enumerable:!0,get:function(){for(var a=[],b=this.next;;){a.push(b);if(b==this)break;b=b.next}return a}},radian:{configurable:!0,enumerable:!0,get:function(){var a=this.prev,b=this.next;return Math.atan2(b.y-a.y,b.x-a.x)}},prevCp:{configurable:!0,enumerable:!0,get:function(){var a=this.radian,b=.2*this.getDistance(this.prev);return new Actor(this.x-Math.cos(a)*b,this.y-Math.sin(a)*b)}},nextCp:{configurable:!0,enumerable:!0,get:function(){var a=
this.radian,b=.2*this.getDistance(this.next);return new Actor(this.x+Math.cos(a)*b,this.y+Math.sin(a)*b)}}});var EnclosingLine=function(a,b){Actor.call(this,void 0===a?-2:a,void 0===b?-2:b,110);this.type="Enclosure";this.lineStyle="Solid";this.holdable=!0;this.root=this.addHandle(this.x,this.y)};$jscomp.inherits(EnclosingLine,Actor);EnclosingLine.prototype.addHandle=function(a,b){a=new ActorHandle(a,b,this.z+1);a.parent=this;this.root&&this.root.add(a);this.reserve(a);return a};
EnclosingLine.prototype.delHandle=function(a){this.root=a.prev;a.eject()};EnclosingLine.prototype.eject=function(){Actor.prototype.eject.call(this);this.root.listAll.forEach(function(a){a.eject()})};EnclosingLine.prototype.isHit=function(a,b){var c=this;this.root.listAll.forEach(function(d){d.isLineHit(a,b)&&(c.hit=!0)});return this.hit};EnclosingLine.prototype.move=function(a,b){Actor.prototype.move.call(this,a,b);this.root.listAll.forEach(function(c){c.move(a,b)})};
EnclosingLine.prototype.createFormData=function(){return this.root.listAll};EnclosingLine.createDefault=function(){var a=new EnclosingLine;a.addHandle(-2,2);a.addHandle(2,2);a.addHandle(2,-2);return a};document.addEventListener("DOMContentLoaded",function(){var a=new EditorMain,b=function(){var c=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame;a.control();a.draw();c(b)};b()});
var EditorMain=function(){this.diagramId=document.querySelector('[name="id"]').value;this.documentId=document.querySelector('[name="documentId"]').value;this.controller=new Controller;this.field=new Field(1024,768);this.pane=document.getElementById("pane");this.isPanel="true"!=this.pane.getAttribute("data-draggable");this.settingPanel=new SettingPanel(this);this.inputPanel=new InputPanel(this);this.partnerPanel=new PartnerPanel(this);this.relationPanel=new RelationPanel(this);this.paneList=[this.inputPanel,
this.partnerPanel,this.relationPanel];this.enclosurePopup=new EnclosurePopup;this.init()};EditorMain.prototype.openPane=function(a,b,c){c=void 0===c?null:c;this.paneList.forEach(function(d){d==a?d.open(b,c):d.hidePane()});$(this.pane).show()};EditorMain.prototype.closePane=function(){this.isPanel?this.paneList.forEach(function(a){a.hidePane()}):$(this.pane).hide();this.settingPanel.close()};
EditorMain.prototype.init=function(){this.isPanel||(this.pane.style.position="absolute",this.pane.style.opacity=.97,$(this.pane).draggable(),$(this.pane).hide());0==this.diagramId.length||0==this.documentId.length?this.initSandbox():this.loadDiagram()};
EditorMain.prototype.initSandbox=function(){Tally.reset();var a=this.field.clearAll(),b=document.querySelector('[name="default.name"]'),c=document.querySelector('[name="default.gender"]'),d=document.querySelector('[name="default.dob"]');EditorMain.DEBUG&&(a.name="principal(\u672c\u4eba)");b.value&&(a.name=b.value);a.gender=c.value;a.dob=d.value};EditorMain.prototype.addEnclosure=function(){this.field.actorList.push(EnclosingLine.createDefault())};
EditorMain.prototype.makePersonMap=function(a){var b={};a.forEach(function(a){b[a.id]=Person.createFromEntity(a)});return b};EditorMain.prototype.loadDiagram=function(){var a=this,b=new DiagramEntity;console.log("[loadDiagram]:BEGIN");b.select(this.diagramId).then(function(b){var c=a.makePersonMap(b.personList);a.settingPanel.loadDiagram(b);a.loadPersons(b,c);a.loadPartner(b,c);a.loadRelationship(b,c);a.loadShapes(b);console.log("[loadDiagram]:END")})};
EditorMain.prototype.loadPersons=function(a,b){var c=this,d=0,e=[];b[a.personId].principal=!0;a.personList.forEach(function(a){var f=b[a.id];console.log("*** #"+a.seq+"."+f.info+" ***");d=a.seq;null==a.prevId?c.field.root.assignActor(f):f.prevActor=b[a.prevId];if(a.parents){a=a.parents;var h=b[a.person.id],k=b[a.other.id];console.log("  *  father:"+h.info+"/mother:"+k.info);h=c.field.createPair(h,k);h.id=a.id;h.type=a.type;f.addParents(h,!1);e.push(h)}c.field.addActor(f)});Tally.reset(d);e.forEach(function(a){a.children.sort(function(a,
b){return a.bornOrder-b.bornOrder})})};EditorMain.prototype.loadPartner=function(a,b){var c=this;a.partnerList.forEach(function(a){var d=b[a.person.id],f=c.field.createPair(d,b[a.other.id]);0<f.children.length||(f.id=a.id,f.type=a.type,d.addPartner(f,!1),c.field.addActor(f))})};EditorMain.prototype.loadRelationship=function(a,b){var c=this;a.relationshipList.forEach(function(a){a=Relationship.create(a.emotion,b[a.person.id],b[a.other.id]);c.field.addActor(a)})};
EditorMain.prototype.loadShapes=function(a){var b=this,c={};a.shapesList.forEach(function(a){if(null==a.parentId){var b=new EnclosingLine(a.x,a.y);b.lineStyle=a.lineStyle;c[a.id]=b}});a.shapesList.forEach(function(a){null!=a.parentId&&c[a.parentId].addHandle(a.x,a.y)});Object.keys(c).forEach(function(a){b.field.addActor(c[a])})};
EditorMain.prototype.onSingleSelection=function(){var a=this.controller.keys;a.Control||a.Shift||a.k16||a.k17||(a=this.field.targetList[0],a instanceof Person?this.openPane(this.inputPanel,a):a instanceof Relation?this.openPane(this.partnerPanel,a):a instanceof Relationship&&this.openPane(this.relationPanel,a))};
EditorMain.prototype.onMultiSelection=function(){var a=this.field.targetList[0],b=this.field.targetList[1];if(a instanceof Person&&b instanceof Person){var c=this.field.getRelationship(a,b);c?this.openPane(this.relationPanel,c):this.openPane(this.relationPanel,a,b)}};
EditorMain.prototype.control=function(){this.field.control();this.field.arrange();var a=this.field.targetList,b=a.length;if(Controller.Instance.contextmenu){var c=this.field.hold;a[0]||c?c instanceof ActorHandle&&this.enclosurePopup.open(c):0==b&&this.settingPanel.open()}if(this.field.targetChanged)if(1==b)this.onSingleSelection();else if(2<=b)this.onMultiSelection();else 0==b&&this.closePane()};EditorMain.prototype.draw=function(){this.field.draw()};EditorMain.DEBUG=!1;EditorMain.PANEL_DODGE=!1;
