var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};
$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
$jscomp.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6-impl","es3");$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");var Actor=function(){this.z=this.y=this.x=0};Actor.prototype.isHit=function(a,b){return!1};
Actor.prototype.eject=function(){this.isGone=!0};Actor.prototype.react=function(){return[]};Actor.prototype.draw=function(a){};var Chain=function(a,b){a=void 0===a?null:a;Actor.call(this);this.id=null==a?UUID.toString():a;this.gender=b;this.parents=null;this.partnerList=[];this.childrenMap={}};$jscomp.inherits(Chain,Actor);Chain.prototype.attributeChanged=function(){};Chain.prototype.listOccupancy=function(a){this.partnerList.forEach(function(a){});return{left:1,right:1}};
Chain.prototype.addParents=function(a){a.mother.addPartner(a.father);a.addChild(this);this.parents=a};Chain.prototype.addPartner=function(a){this.partnerList.push(a);a.partnerList.push(this)};Chain.prototype.listChildren=function(a){var b=[];a=this.childrenMap[a.id];if(!a)return b;a.forEach(function(a){var c=a.partnerList;a.isMale?(b.push(a),b=b.concat(c)):(b=b.concat(c),b.push(a))});return b};
$jscomp.global.Object.defineProperties(Chain.prototype,{gender:{configurable:!0,enumerable:!0,get:function(){return this._gender},set:function(a){this._gender=a;this.attributeChanged()}},isMale:{configurable:!0,enumerable:!0,get:function(){return"m"==this.gender}},mother:{configurable:!0,enumerable:!0,get:function(){return this.parents?this.parents.mother:null}},father:{configurable:!0,enumerable:!0,get:function(){return this.parents?this.parents.father:null}},numOfPartner:{configurable:!0,enumerable:!0,
get:function(){return this.partnerList.length}}});var Controller=function(a){this.keys={};this.point={};this.touch=!1;this.init(void 0===a?!1:a);Controller.Instance=this};Controller.prototype.init=function(a){a||window.addEventListener("contextmenu",function(a){a.preventDefault()});this.initKeys();this.initPointingDevice()};
Controller.prototype.initKeys=function(){var a=this;window.addEventListener("keydown",function(b){b.key?a.keys[b.key]=!0:a.keys["k"+b.keyCode]=!0});window.addEventListener("keyup",function(b){b.key?delete a.keys[b.key]:delete a.keys["k"+b.keyCode]})};
Controller.prototype.initPointingDevice=function(){var a=this,b=document.getElementById("canvas"),c=function(){a.touch=!1;a.point=null};b.addEventListener("mousedown",function(b){a.touch=!0;a.point=FlexibleView.Instance.convert(b.clientX,b.clientY)});b.addEventListener("mousemove",function(b){a.touch&&(a.point=FlexibleView.Instance.convert(b.clientX,b.clientY))});b.addEventListener("mouseup",function(){return c()});b.addEventListener("mouseleave",function(){return c()});b.addEventListener("touchstart",
function(b){var c=b.touches[0];a.touch=!0;a.point=FlexibleView.Instance.convert(c.pageX,c.pageY);b.preventDefault()});b.addEventListener("touchmove",function(b){b=b.touches[0];a.touch=!0;a.point=FlexibleView.Instance.convert(b.pageX,b.pageY)});b.addEventListener("touchend",function(){return c()})};var EnclosingLine=function(){Actor.call(this);this.y=this.x=100;this.radius=10;this.points=[];this.addPoint(200,100);this.addPoint(200,200);this.addPoint(100,200)};$jscomp.inherits(EnclosingLine,Actor);
EnclosingLine.prototype.addPoint=function(a,b){this.points.push({x:a,y:b})};EnclosingLine.prototype.isHit=function(a,b){var c=this,d=null;this.list.forEach(function(e){e.hit=!1;if(!d){var f=e.x-a,g=e.y-b;Math.sqrt(f*f+g*g)<c.radius&&(d=e,e.hit=c)}});return d};EnclosingLine.prototype.drawLine=function(a){a.beginPath();a.moveTo(this.x,this.y);this.points.forEach(function(b){a.lineTo(b.x,b.y)});a.lineTo(this.x,this.y);a.strokeStyle="lightglay";a.stroke()};
EnclosingLine.prototype.drawHandle=function(a){var b=this;this.list.forEach(function(c){c.hit&&(a.beginPath(),a.strokeStyle="aqua",a.arc(c.x,c.y,b.radius,0,2*Math.PI,!1),a.stroke())})};EnclosingLine.prototype.draw=function(a){var b=this.list,c=b.length;a.save();a.moveTo(this.x,this.y);for(var d=0;d<c-1;d++){var e=b[d],f=b[d+1];a.quadraticCurveTo(e.x,e.y,f.x,f.y);a.lineTo(e.x,e.y)}a.strokeStyle="green";a.stroke();this.drawHandle(a);a.restore()};
$jscomp.global.Object.defineProperties(EnclosingLine.prototype,{list:{configurable:!0,enumerable:!0,get:function(){return this.points.concat(this)}}});var Field=function(a,b){this.width=a;this.height=b;this.view=new FlexibleView(a,b);this.ty=this.tx=0;this.focus=null;this.targetList=[];this.actorList=[];this.dirty=!1;this.setupEvents();Field.Instance=this};
Field.prototype.getRelationship=function(a,b){var c=null;this.actorList.forEach(function(d){!c&&d instanceof Relationship&&(d.person==a&&d.other==b||d.person==b&&d.other==a)&&(c=d)});return c};
Field.prototype.setupEvents=function(){var a=this,b=this.view.view,c=Controller.Instance.keys;b.addEventListener("mousedown",function(b){b=a.view.convert(b.clientX,b.clientY);b=a.scan(b.x,b.y);c.Control||c.Shift||c.k16||c.k17||(a.targetList=[]);b&&a.targetList.push(b);a.hold=b});b.addEventListener("mouseup",function(b){a.hold=null});b.addEventListener("mousemove",function(b){b=a.view.convert(b.clientX,b.clientY);if(a.hold){var c=b.y-a.ty;a.hold.x=b.x-a.tx;a.hold.y=c}else a.scan(b.x,b.y)})};
Field.prototype.setFocus=function(a){this.focus=a;this.dirty=!0};Field.prototype.addActor=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];var d=this;b.forEach(function(a){d.actorList.push(a)});this.dirty=!0};Field.prototype.scan=function(a,b){var c=null,d=a-this.tx,e=b-this.ty;this.actorList.forEach(function(a){a.hit=!1;c||a.isHit(d,e)&&(c=a)});return c};Field.prototype.clearSelection=function(){this.scan(Number.MAX_VALUE,Number.MAX_VALUE);this.targetList=[]};
Field.prototype.arrange=function(){if(this.dirty){console.log("dirty.");this.dirty=!1;var a=0,b=0,c=0,d=0,e=[];this.focus.x=0;this.focus.y=0;this.focus.scanAll(e);console.log("list:"+e.length);Tally.reset();this.focus.calculate();e.forEach(function(a){e.forEach(function(b){a!=b&&a.touch(b)})});e.forEach(function(e){var f=e.x;e=e.y;a=Math.min(a,f);b=Math.min(b,e);c=Math.max(c,f);d=Math.max(d,e)});var f=(this.height-(d-b))/2;this.tx=(this.width-(c-a))/2-a;this.ty=f-b}};
Field.prototype.choiceActor=function(){var a=[];this.actorList.forEach(function(b){b.isGone||a.push(b)});a.sort(function(a,c){return a.z-c.z});this.actorList=a};
Field.prototype.drawGrid=function(a){if(this.showGrid){var b=this.width/2,c=this.height/2,d=this.spacing/2,e=-c,f=-b;a.save();a.lineWidth=.2;a.strokeStyle="aqua";a.translate(b,c);for(var g=0;g<b;g+=d)a.beginPath(),a.moveTo(g,e),a.lineTo(g,c),a.stroke(),0<g&&(a.beginPath(),a.moveTo(-g,e),a.lineTo(-g,c),a.stroke());for(e=0;e<c;e+=d)a.beginPath(),a.moveTo(f,e),a.lineTo(b,e),a.stroke(),0<e&&(a.beginPath(),a.moveTo(f,-e),a.lineTo(b,-e),a.stroke());a.restore()}};
Field.prototype.draw=function(){var a=this,b=this.view.ctx,c=this.fontSize;this.view.clear();this.choiceActor();this.drawGrid(b);b.save();b.font=c+"px 'Times New Roman'";b.textBaseline="middle";b.translate(this.tx,this.ty);this.actorList.forEach(function(d){d.fontSize=c;d.selected=-1!=a.targetList.indexOf(d);d.draw(b)});b.restore()};
$jscomp.global.Object.defineProperties(Field.prototype,{showGrid:{configurable:!0,enumerable:!0,get:function(){return document.querySelector('[name="grid"]').checked}},spacing:{configurable:!0,enumerable:!0,get:function(){var a=document.querySelector('[name="gridSpacing"]');(a=parseFloat(a.value))||(a=160);return a}},fontSize:{configurable:!0,enumerable:!0,get:function(){var a=document.querySelector('[name="fontSize"]');(a=parseFloat(a.value))||(a=12);return a}}});
var FlexibleView=function(a,b){this.view=document.getElementById("view");this.canvas=document.getElementById("canvas");this.ctx=this.canvas.getContext("2d");this.scale=1;this.init();this.setSize(a,b);FlexibleView.Instance=this};FlexibleView.prototype.setSize=function(a,b){this.width=a;this.height=b;this.canvas.width=a;this.canvas.height=b;this.resize()};
FlexibleView.prototype.init=function(){var a=this,b=document.querySelector('[data-role="header"]'),c=document.querySelector('[data-role="footer"]');this.headerHeight=b?b.offsetHeight:0;this.footerHeight=c?c.offsetHeight:0;this.margin=this.headerHeight+this.footerHeight;window.addEventListener("resize",function(){a.resize()});window.addEventListener("keydown",function(){view.classList.contains("addicting")||view.classList.add("addicting")});window.addEventListener("mousemove",function(){view.classList.remove("addicting")})};
FlexibleView.prototype.resize=function(){var a=document.body.clientWidth/this.width,b=(window.innerHeight-this.margin)/this.height;this.scale=b<a?b:a;this.view.setAttribute("style",["width:"+this.width+"px","height:"+this.height+"px","transform: scale("+this.scale+")"].join(";"))};FlexibleView.prototype.convert=function(a,b){return{x:a/this.scale,y:(b-this.headerHeight)/this.scale}};FlexibleView.prototype.clear=function(){this.ctx.clearRect(0,0,this.width,this.height)};
var GenoCalendar=function(a){this.day=this.month=this.year=null;a&&this.setupDate(new String(a))};GenoCalendar.prototype.setupDate=function(a){var b=a.split(/[-/]/g);a=(new Date).getFullYear()+1;var c=parseInt(b[0]);Number.isFinite(c)?c+1900<a&&(c+=1900):c=null;this.year=c;if(1<b.length){a=parseInt(b[1]);if(2<b.length)b=new Date(c,a-1,parseInt(b[2])),b.getFullYear(),a=b.getMonth()+1,this.day=b=b.getDate();else if(0>a||12<a)a=1;this.month=a}};
GenoCalendar.prototype.toString=function(){var a=[];this.year&&(a.push(this.year),this.month&&(a.push(this.month),this.day&&a.push(this.day)));return a.join("-")};
$jscomp.global.Object.defineProperties(GenoCalendar.prototype,{age:{configurable:!0,enumerable:!0,get:function(){if(!this.year)return null;var a=new Date,b=a.getFullYear();if(!this.month)return b-this.year;var c=a.getMonth()+1;if(!this.dd)return Math.floor((100*b+c-(100*this.year+this.month))/100);a=a.getDate();return Math.floor((1E4*b+100*c+a-(1E4*this.year+100*this.month+this.day))/1E4)}}});var InputPanel=function(){this.panel=document.getElementById("inputPanel");this.person=null;this.setupEvents()};
InputPanel.prototype.setupEvents=function(){var a=this,b=this.panel.querySelector('[name="name"]'),c=$('[name="gender"]'),d=this.panel.querySelector('[name="dob"]'),e=this.panel.querySelector('[name="dod"]'),f=this.panel.querySelector('[name="age"]'),g=document.getElementById("parentsButton"),h=document.getElementById("partnerButton");b.addEventListener("change",function(){a.person.name=b.value});c.click(function(b){a.person.gender=b.target.value;a.refreshControls()});d.addEventListener("keyup",function(){var b=
(new GenoCalendar(d.value)).toString();a.person.dob=b;f.value=a.person.age});d.addEventListener("change",function(){var a=new GenoCalendar(d.value);d.value=a.toString()});e.addEventListener("keyup",function(){var b=(new GenoCalendar(e.value)).toString();a.person.dod=b;f.value=a.person.age});e.addEventListener("change",function(){var a=new GenoCalendar(e.value);e.value=a.toString()});f.addEventListener("keyup",function(){return a.ageChanged()});g.addEventListener("click",function(){return a.addParents()});
h.addEventListener("click",function(){return a.addPartner()});$(this.panel).panel({close:function(){Field.Instance.clearSelection()}});$(h).addClass("ui-state-disabled")};InputPanel.prototype.ageChanged=function(){var a=this.panel.querySelector('[name="dob"]');this.panel.querySelector('[name="dod"]');var b=this.panel.querySelector('[name="age"]'),b=parseInt(b.value);this.person.age=null;if(b){var c=(new Date).getFullYear()-b;a.value=c;this.person.dob=c;this.person.age=b}};
InputPanel.prototype.addParents=function(){var a=new Person(null,"m"),b=new Person(null,"f"),c=new Relation(a,b);this.person.addParents(c);this.refreshControls();Field.Instance.addActor(a,b,c)};InputPanel.prototype.addPartner=function(){var a=new Person(null,this.person.isMale?"f":"m"),b=new Relation(this.person,a);this.person.addPartner(a);this.refreshControls();Field.Instance.addActor(a,b)};
InputPanel.prototype.refreshControls=function(){var a=this.person.mother,b=this.person.gender,c=this.person.partnerList.length,d=Object.keys(this.person.childrenMap).length,e=document.getElementById("parentsButton"),f=document.getElementById("partnerButton"),g=document.getElementById("deleteButton");0==c?$('[name="gender"]').checkboxradio("enable"):$('[name="gender"]').checkboxradio("disable");a?$(e).addClass("ui-state-disabled"):$(e).removeClass("ui-state-disabled");null==b||""==b?$(f).addClass("ui-state-disabled"):
$(f).removeClass("ui-state-disabled");0==c&&0==d?$(g).removeClass("ui-state-disabled"):$(g).addClass("ui-state-disabled");Field.Instance.dirty=!0};InputPanel.prototype.setupForm=function(){var a=this;$("#inputPanel form :input").each(function(b,c){b=c.getAttribute("name");var d=c.getAttribute("type"),e=a.person[b];"radio"==d?$(c).val([e]).checkboxradio("refresh"):(console.log(b+":"+e),$(c).val(e))});this.refreshControls()};InputPanel.prototype.open=function(a){this.person=a;this.setupForm();$(this.panel).panel("open")};
var PartnerPanel=function(){this.panel=document.getElementById("partnerPanel");this.relation=null;this.setupEvents()};PartnerPanel.prototype.setupEvents=function(){var a=this,b=document.getElementById("mChildButton"),c=document.getElementById("fChildButton"),d=function(b){b=new Person(null,b);a.relation.addChild(b);Field.Instance.addActor(b)};b.addEventListener("click",function(){d("m")});c.addEventListener("click",function(){d("f")});$(this.panel).panel({close:function(){Field.Instance.clearSelection()}})};
PartnerPanel.prototype.setupForm=function(){var a=this.panel.querySelector('[name="father"]'),b=this.panel.querySelector('[name="mother"]');a.value=this.relation.father.info;b.value=this.relation.mother.info};PartnerPanel.prototype.open=function(a){this.relation=a;this.setupForm();$(this.panel).panel("open")};var Person=function(a,b){Chain.call(this,void 0===a?null:a,void 0===b?"":b);this.dod=this.dob=this.description=this.name="";this.radius=32;this.principal=!1};$jscomp.inherits(Person,Chain);
Person.prototype.attributeChanged=function(){this.symbol=this.isMale?new MaleSymbol(this):new FemaleSymbol(this)};Person.prototype.scanAll=function(a,b){b=void 0===b?0:b;var c=this;-1===a.indexOf(this)&&(this.depth=b,this.touched=this.fixed=!1,a.push(this),this.mother&&this.mother.scanAll(a,b-1),this.partnerList.forEach(function(d){var e=c.listChildren(d);d.scanAll(a,b);e.forEach(function(c){c.scanAll(a,b+1)})}))};
Person.prototype.calculate=function(){var a=this;if(!this.fixed){var b=Field.Instance.spacing,c=b/2;this.mother&&!this.mother.fixed?(this.mother.x=this.x+c,this.mother.y=this.y-b,this.mother.calculate()):(this.count=Tally.increment(),this.fixed=!0,this.partnerList.forEach(function(d){var e=a.listChildren(d),f=a.x-c-b*(e.length-1)/2,g=a.y+b;console.log("#"+a.count+" childrenList:"+e.length);d.fixed||(d.x=a.x+b*("m"==d.gender?-1:1),d.y=a.y,console.log("partner#"+d.count+":"+d.x),d.calculate());e.forEach(function(a){console.log("child#"+
a.count+" cx:"+f);a.x=f;a.y=g;a.calculate();f+=b})}))}};Person.prototype.touch=function(a){var b=this.x-a.x;a=this.y-a.y;Math.sqrt(b*b+a*a)<Field.Instance.spacing&&(this.touched=!0);return this.touched};Person.prototype.isHit=function(a,b){return this.hit=this.symbol.isHit(a,b)};
Person.prototype.drawSymbol=function(a){this.selected?(this.strokeStyle="navy",a.lineWidth=5):this.hit?(this.strokeStyle="aqua",a.lineWidth=5):(this.strokeStyle="black",a.lineWidth=2);a.strokeStyle=this.strokeStyle;this.touched&&(a.strokeStyle="red");this.symbol.draw(a)};
Person.prototype.drawChildLine=function(a){var b=this;if(0!=Object.keys(this.childrenMap).length){var c=Field.Instance.spacing/2,d=this.y+c+c/4,e=!0,f=null;Object.keys(this.childrenMap).forEach(function(c){b.childrenMap[c].forEach(function(c){var g=c.parents.rect,h=g.center,g=g.bottom,k=c.x,l=c.y-b.radius;a.beginPath();e&&(a.moveTo(h,g),a.lineTo(h,d),a.lineTo(k,d),e=!1);a.moveTo(k,d);a.lineTo(k,l);a.stroke();f=c});a.beginPath();a.moveTo(f.parents.rect.center,d);a.lineTo(f.x,d);a.stroke()})}};
Person.prototype.draw=function(a){a.save();this.drawChildLine(a);a.translate(this.x,this.y);this.drawSymbol(a);a.restore()};$jscomp.global.Object.defineProperties(Person.prototype,{age:{configurable:!0,enumerable:!0,get:function(){return(new GenoCalendar(this.dob)).age}},info:{configurable:!0,enumerable:!0,get:function(){var a=this.name,b=this.age;b&&(a+="("+b+")");return a}}});
var Relation=function(a,b){Actor.call(this);a.isMale?(this.father=a,this.mother=b):(this.father=b,this.mother=a);this.ranking=0;this.hit=!1};$jscomp.inherits(Relation,Actor);Relation.prototype.addChild=function(a){var b=this.mother,c=this.father.id,d=b.childrenMap[c];d||(d=[],b.childrenMap[c]=d);a.parents=this;d.push(a)};Relation.prototype.isHit=function(a,b){var c=this.rect;this.hit=!1;c.left<=a&&a<=c.right&&c.top<=b&&b<=c.bottom&&(this.hit=!0);return this.hit};
Relation.prototype.drawNormal=function(a){var b=this.rect;a.beginPath();a.moveTo(b.left,b.top);a.lineTo(b.left,b.bottom);a.lineTo(b.right,b.bottom);a.lineTo(b.right,b.top);a.stroke()};Relation.prototype.drawHighlight=function(a){a.strokeStyle="aqua";a.lineWidth=5;this.drawNormal(a)};Relation.prototype.draw=function(a,b){a.save();this.hit?this.drawHighlight(a):this.drawNormal(a);a.restore()};
$jscomp.global.Object.defineProperties(Relation.prototype,{rect:{configurable:!0,enumerable:!0,get:function(){var a=this.father,b=this.mother,c=a.y+a.radius,d=Math.min(a.x,b.x),a=Math.abs(a.x-b.x),b=Field.Instance.spacing/2/4;return{top:c,left:d,right:d+a,bottom:c+b,center:d+a/2,width:a,height:b}}}});var RelationPanel=function(){this.panel=document.getElementById("relationPanel");this.deleteButton=this.panel.querySelector('[name="deleteButton"]');this.to=this.from=null;this.setupEvents()};
RelationPanel.prototype.setupEvents=function(){var a=this;$('[name="emotion"]').click(function(){a.deleteRelationship();a.relationship=a.createRelationship();a.resetControls()});this.deleteButton.addEventListener("click",function(){a.deleteRelationship();a.resetControls()});$(this.panel).panel({close:function(){Field.Instance.clearSelection()}})};
RelationPanel.prototype.createRelationship=function(){var a=$('[name="emotion"]:checked'),a=Relationship.create(a.val(),this.from,this.to);a.hit=!0;Field.Instance.addActor(a);return a};RelationPanel.prototype.deleteRelationship=function(){this.relationship&&(this.relationship.eject(),this.relationship=null)};RelationPanel.prototype.resetControls=function(){this.relationship?$(this.deleteButton).show():$(this.deleteButton).hide()};
RelationPanel.prototype.setupForm=function(){var a=this.panel.querySelector('[name="from"]'),b=this.panel.querySelector('[name="to"]'),c=$('[name="emotion"]');a.value=this.from.info;b.value=this.to.info;this.relationship?c.val([this.relationship.emotion]).checkboxradio("refresh"):c.removeAttr("checked").checkboxradio("refresh");this.resetControls()};
RelationPanel.prototype.open=function(a,b){(b=void 0===b?null:b)?(this.from=a,this.to=b,this.relationship=null,this.isNew=!0):(this.from=a.person,this.to=a.other,this.relationship=a,this.isNew=!1);this.setupForm();$(this.panel).panel("open")};var Tally=function(){};Tally.reset=function(){Tally.val=0};Tally.increment=function(){return++Tally.val};Tally.val=0;var UUID=function(){};UUID.toString=function(){return UUID.Format.replace(/X|Y/g,function(a){var b=16*Math.random()|0;return("X"===a?b:b&3|8).toString(16)})};
UUID.Format="XXXXXXXX-XXXX-4XXX-YXXX-XXXXXXXXXXXX";var GenoSymbol=function(a){this.person=a};GenoSymbol.prototype.drawSymbol=function(a){var b=2*this.radius;a.strokeRect(-this.radius,-this.radius,b,b);if(this.person.principal){var b=this.ir,c=2*b;a.strokeRect(-b,-b,c,c)}};GenoSymbol.prototype.drawCross=function(a){var b=-this.radius,c=-this.radius,d=this.radius,e=this.radius;a.beginPath();a.moveTo(c,b);a.lineTo(d,e);a.stroke();a.beginPath();a.moveTo(d,b);a.lineTo(c,e);a.stroke()};
GenoSymbol.prototype.drawYears=function(a){new GenoCalendar(this.person.dob);var b=new GenoCalendar(null);var c=new GenoCalendar(this.person.dod);b=[b.year,c.year].join("-");1>=b.length||a.fillText(b,0,-(this.textHh+this.radius))};GenoSymbol.prototype.drawAge=function(a){var b=this.person.age;b&&(a.strokeText(b,0,0),a.fillText(b,0,0))};GenoSymbol.prototype.drawName=function(a){a.fillText(this.person.name,0,this.textHh+this.radius)};
GenoSymbol.prototype.resetProperties=function(){this.radius=this.person.radius;this.width=2*this.radius;this.ir=.8*this.radius;this.fontSize=this.person.fontSize;this.textMargin=.2*this.fontSize;this.textHh=this.fontSize/2+this.textMargin};
GenoSymbol.prototype.draw=function(a){this.resetProperties();a.save();a.strokeStyle=this.person.strokeStyle;a.textAlign="center";this.drawSymbol(a);this.person.dod&&this.drawCross(a);a.lineWidth=1;a.strokeStyle="black";a.fillStyle="black";this.drawAge(a);this.drawYears(a);this.drawName(a);a.restore()};var FemaleSymbol=function(a){GenoSymbol.apply(this,arguments)};$jscomp.inherits(FemaleSymbol,GenoSymbol);
FemaleSymbol.prototype.isHit=function(a,b){var c=this.person;a=c.x-a;b=c.y-b;return Math.sqrt(a*a+b*b)<c.radius};FemaleSymbol.prototype.drawSymbol=function(a){a.beginPath();a.arc(0,0,this.radius,0,2*Math.PI,!1);a.stroke();this.person.principal&&(a.beginPath(),a.arc(0,0,this.ir,0,2*Math.PI,!1),a.stroke())};
FemaleSymbol.prototype.drawCross=function(a){var b=Math.PI/2,c=b/2,d=Math.cos(c+b)*this.radius,b=-Math.sin(c+b)*this.radius,e=Math.sin(c)*this.radius,c=Math.cos(-c)*this.radius;a.beginPath();a.moveTo(b,d);a.lineTo(e,c);a.stroke();a.beginPath();a.moveTo(e,d);a.lineTo(b,c);a.stroke()};var MaleSymbol=function(a){GenoSymbol.apply(this,arguments)};$jscomp.inherits(MaleSymbol,GenoSymbol);
MaleSymbol.prototype.isHit=function(a,b){var c=this.person;b=c.y-b;var d=c.radius;return Math.abs(c.x-a)<d&&Math.abs(b)<d};var Relationship=function(a,b){Actor.call(this);this.person=a;this.other=b;this.createFillStyle()};$jscomp.inherits(Relationship,Actor);
Relationship.prototype.createFillStyle=function(a){a=void 0===a?null:a;var b=this,c=FlexibleView.Instance.ctx;this.height=16;this.fillStyle="rgba(200, 200, 255, 0.7)";this.img=new Image;this.img.onload=function(){b.height=b.img.height;b.fillStyle=c.createPattern(b.img,"repeat-x")};a&&(this.img.src=a)};
Relationship.prototype.calculatePosition=function(){this.bx=this.person.x;this.by=this.person.y;this.ex=this.other.x;this.ey=this.other.y;var a=this.ex-this.bx,b=this.ey-this.by;this.cx=this.bx+a/2;this.cy=this.by+b/2;this.radian=Math.atan2(b,a);this.length=Math.sqrt(a*a+b*b);this.width=this.length-(this.person.radius+this.other.radius)};
Relationship.prototype.isHit=function(a,b){a=this.cx-a;var c=this.cy-b,d=-this.radian;b=Math.cos(d)*a-Math.sin(d)*c;a=Math.sin(d)*a+Math.cos(d)*c;var c=-this.length/2+this.person.radius,d=-this.height/2,e=this.width+c,f=this.height+d;return this.hit=c<=b&&b<=e&&d<=a&&a<=f};
Relationship.prototype.drawAuxiliary=function(a){a.save();a.strokeStyle="blue";a.beginPath();a.moveTo(this.bx,this.by);a.lineTo(this.ex,this.ey);a.stroke();a.fillStyle="red";a.beginPath();a.arc(this.bx,this.by,4,0,2*Math.PI,!1);a.fill();a.beginPath();a.arc(this.ex,this.ey,4,0,2*Math.PI,!1);a.fill();a.beginPath();a.arc(this.cx,this.cy,4,0,2*Math.PI,!1);a.fill();a.restore()};
Relationship.prototype.draw=function(a){this.calculatePosition();var b=-this.length/2+this.person.radius,c=-this.height/2;a.save();a.translate(this.cx,this.cy);a.rotate(this.radian);a.translate(b,c);a.fillStyle=this.fillStyle;a.fillRect(0,0,this.width,this.height);this.hit&&(a.fillStyle="rgba(140, 255, 255, 0.5)",a.fillRect(0,0,this.width,this.height));a.restore()};
Relationship.create=function(a,b,c){b="fused"==a?new FusedRelation(b,c):"close"==a?new CloseRelation(b,c):"distant"==a?new DistantRelation(b,c):"hostile"==a?new HostileRelation(b,c):new Relationship(b,c);b.emotion=a;return b};var CloseRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.close.png")};$jscomp.inherits(CloseRelation,Relationship);CloseRelation.create=Relationship.create;var DistantRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.distant.png")};
$jscomp.inherits(DistantRelation,Relationship);DistantRelation.create=Relationship.create;var FusedRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/ralation.fused.png")};$jscomp.inherits(FusedRelation,Relationship);FusedRelation.create=Relationship.create;var HostileRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.hostile.png")};$jscomp.inherits(HostileRelation,Relationship);HostileRelation.create=Relationship.create;
document.addEventListener("DOMContentLoaded",function(){var a=new AppMain,b=function(){var c=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame;a.draw();c(b)};b()});var AppMain=function(){this.controller=new Controller;this.field=new Field(1024,768);this.inputPanel=new InputPanel;this.partnerPanel=new PartnerPanel;this.relationPanel=new RelationPanel;this.setupEvents();this.init()};
AppMain.prototype.setupEvents=function(){var a=this,b=document.getElementById("view"),c=$('[name="gridSpacing"]');b.addEventListener("click",function(){if(0!=a.field.targetList.length){var b=a.field.targetList[0],c=a.controller.keys;if(!(c.Control||c.Shift||c.k16||c.k17)){if(b instanceof Person){a.inputPanel.open(b);return}if(b instanceof Relation){a.partnerPanel.open(b);return}if(b instanceof Relationship){a.relationPanel.open(b);return}}if(2<=a.field.targetList.length){var c=a.field.targetList[1],
f=a.field.getRelationship(b,c);f?a.relationPanel.open(f):a.relationPanel.open(b,c)}}});c.change(function(){a.field.dirty=!0})};AppMain.prototype.init=function(){var a=new Person;a.principal=!0;this.field.setFocus(a);this.field.actorList.push(a)};AppMain.prototype.draw=function(){this.field.arrange();this.field.draw()};
