var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.EXPOSE_ASYNC_EXECUTOR=!0;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var c=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){c(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}};d.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=
!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),
a[b]=null;this.onSettledCallbacks_=null}};var e=new b;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};d.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(m){f(m)}}:b}var e,f,g=new d(function(a,b){e=a;f=b});this.callWhenSettled_(c(a,e),
c(b,f));return g};d.prototype.catch=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?e.asyncExecute(c):this.onSettledCallbacks_.push(function(){e.asyncExecute(c)})};d.resolve=function(a){return a instanceof d?a:new d(function(b,c){b(a)})};d.reject=function(a){return new d(function(b,c){c(a)})};
d.race=function(a){return new d(function(b,c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())d.resolve(f.value).callWhenSettled_(b,c)})};d.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?d.resolve([]):new d(function(a,e){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,d.resolve(c.value).callWhenSettled_(f(g.length-1),e),c=b.next();while(!c.done)})};$jscomp.EXPOSE_ASYNC_EXECUTOR&&(d.$jscomp$new$AsyncExecutor=function(){return new b});
return d},"es6-impl","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6-impl","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;for(c=c||0;c<e;c++)if(b[c]==a||Object.is(b[c],a))return!0;return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6-impl","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
$jscomp.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6-impl","es3");$jscomp.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6-impl","es3");$jscomp.polyfill("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991},"es6-impl","es3");var AjaxUtils=function(){};
AjaxUtils.fetch=function(a,b){if("function"===typeof fetch)return console.log("AjaxUtils.fetch:"+a),fetch(a,{method:"post",body:b,credentials:"include"}).then(function(a){return a.json()});console.log("AjaxUtils.promise:"+a);return new Promise(function(c,d){var e=new XMLHttpRequest;e.open("post",a);e.withCredentials=!0;e.addEventListener("loadend",function(){200<=e.status&&300>e.status?c(JSON.parse(e.response)):d(e.statusText)});e.send(b)})};AjaxUtils.post=function(a,b){return AjaxUtils.fetch(a,b)};
var Tally=function(){};Tally.reset=function(){Tally.val=0};Tally.increment=function(){return++Tally.val};Tally.val=0;var AlphabeticalTally=function(){};AlphabeticalTally.increment=function(){for(var a="",b=AlphabeticalTally.val++,c=AlphabeticalTally.Max,d=0;2>d;d++)var e=String.fromCharCode(65+b%c),b=Math.floor(b/c),a=e+a;return a};AlphabeticalTally.val=0;AlphabeticalTally.Max=26;var UUID=function(){};
UUID.toString=function(){return UUID.Format.replace(/X|Y/g,function(a){var b=16*Math.random()|0;return("X"===a?b:b&3|8).toString(16)})};UUID.Format="XXXXXXXX-XXXX-4XXX-YXXX-XXXXXXXXXXXX";var EntityBase=function(a){this.base=a};EntityBase.prototype.list=function(a){a=void 0===a?{}:a;return AjaxUtils.post("/"+this.base+"/list",a)};EntityBase.prototype.select=function(a){var b=new FormData;b.append("id",a);return AjaxUtils.post("/"+this.base+"/select",b)};
EntityBase.prototype.save=function(a){return AjaxUtils.post("/"+this.base+"/save",a)};var DiagramEntity=function(){EntityBase.call(this,"diagram")};$jscomp.inherits(DiagramEntity,EntityBase);var InputPanel=function(){this.panel=document.getElementById("inputPanel");this.person=null;this.setupEvents()};
InputPanel.prototype.setupEvents=function(){var a=this,b=this.panel.querySelector('[name="name"]'),c=this.panel.querySelector('[name="description"]'),d=$('[name="gender"]'),e=this.panel.querySelector('[name="dob"]'),f=this.panel.querySelector('[name="dod"]'),g=this.panel.querySelector('[name="age"]'),h=document.getElementById("parentsButton"),k=document.getElementById("partnerButton"),l=this.panel.querySelector('[name="deleteButton"]');b.addEventListener("change",function(){a.person.name=b.value});
c.addEventListener("change",function(){a.person.description=c.value});d.click(function(b){a.person.gender=b.target.value;a.refreshControls()});e.addEventListener("keyup",function(){var b=(new GenoCalendar(e.value)).toString();a.person.dob=b;g.value=a.person.age});e.addEventListener("change",function(){var a=new GenoCalendar(e.value);e.value=a.toString()});f.addEventListener("keyup",function(){var b=(new GenoCalendar(f.value)).toString();a.person.dod=b;g.value=a.person.age});f.addEventListener("change",
function(){var a=new GenoCalendar(f.value);f.value=a.toString()});g.addEventListener("keyup",function(){return a.ageChanged()});h.addEventListener("click",function(){return a.addParents()});k.addEventListener("click",function(){return a.addPartner()});l.addEventListener("click",function(){return a.person.remove()});$(this.panel).panel({close:function(){Field.Instance.clearSelection()}})};
InputPanel.prototype.ageChanged=function(){var a=this.panel.querySelector('[name="dob"]');this.panel.querySelector('[name="dod"]');var b=this.panel.querySelector('[name="age"]'),b=parseInt(b.value);this.person.age=null;if(b){var c=(new Date).getFullYear()-b;a.value=c;this.person.dob=c;this.person.age=b}};
InputPanel.prototype.addParents=function(){var a=Field.Instance;console.log(a.numOfGeneration+"/min:"+a.minGeneration+"/max:"+a.maxGeneration);console.log("person.generation:"+this.person.generation);if(this.person.generation==a.minGeneration&&a.numOfGeneration==Field.MAX_GENERATION)alert("\u4e16\u4ee3\u6570\u306f\u3001"+Field.MAX_GENERATION+"\u307e\u3067\u306e\u8a2d\u5b9a\u306b\u306a\u3063\u3066\u3044\u307e\u3059\u3002");else{var a=new Person("m"),b=new Person("f"),a=new Relation(a,b);this.person.addParents(a);
this.refreshControls()}};InputPanel.prototype.addPartner=function(){var a=new Person(this.person.isMale?"f":"m"),b=new Relation(this.person,a);this.person.addPartner(b);this.refreshControls();Field.Instance.addActor(a,b)};
InputPanel.prototype.refreshControls=function(){var a=this.person.gender,b=this.person.relationList.length,c=document.getElementById("parentsButton"),d=document.getElementById("partnerButton"),e=this.panel.querySelector('[name="deleteButton"]');0==b?$('[name="gender"]').checkboxradio("enable"):$('[name="gender"]').checkboxradio("disable");this.person.parents?$(c).addClass("ui-state-disabled"):$(c).removeClass("ui-state-disabled");null==a||""==a?$(d).addClass("ui-state-disabled"):$(d).removeClass("ui-state-disabled");
this.person.principal||this.person.hasChild?$(e).addClass("ui-state-disabled"):$(e).removeClass("ui-state-disabled")};InputPanel.prototype.setupForm=function(){var a=this;$("#inputPanel form :input").each(function(b,c){var d=c.getAttribute("name");b=c.getAttribute("type");d=a.person[d];"radio"==b?$(c).val([d]).checkboxradio("refresh"):c.value=d});this.refreshControls()};InputPanel.prototype.open=function(a){this.person=a;this.setupForm();$(this.panel).panel("open")};
var ListviewRow=function(a,b){b=void 0===b?null:b;var c=document.createElement("img"),d=document.createElement("span"),e=document.createElement("p"),f=document.createElement("a"),g=document.createElement("li");null!=b&&c.setAttribute("src",b);d.textContent=a.name;e.textContent=a.description;a.href&&f.setAttribute("href",a.href);f.appendChild(c);f.appendChild(d);f.appendChild(e);a.count&&(b=document.createElement("span"),b.classList.add("ui-li-count"),b.textContent=a.count,f.appendChild(b));g.appendChild(f);
this.img=c;this.anchor=f;this.li=g},PartnerPanel=function(){this.panel=document.getElementById("partnerPanel");this.childrenView=document.getElementById("childrenView");this.relation=null;this.setupEvents()};
PartnerPanel.prototype.setupEvents=function(){var a=this,b=document.getElementById("mChildButton"),c=document.getElementById("fChildButton");$('[name="relationType"]').click(function(){var b=$('[name="relationType"]:checked').val();a.relation.type=b});b.addEventListener("click",function(){a.addChild("m")});c.addEventListener("click",function(){a.addChild("f")});$(this.childrenView).sortable({stop:function(b,c){a.reorganizeChildren()}});$(this.panel).panel({close:function(){Field.Instance.clearSelection()}})};
PartnerPanel.prototype.addChild=function(a){var b=Field.Instance,c=this.relation.father;console.log(b.numOfGeneration+"/min:"+b.minGeneration+"/max:"+b.maxGeneration);b.maxGeneration<=c.generation&&b.numOfGeneration==Field.MAX_GENERATION?alert("\u4e16\u4ee3\u6570\u306f\u3001"+Field.MAX_GENERATION+"\u307e\u3067\u306e\u8a2d\u5b9a\u306b\u306a\u3063\u3066\u3044\u307e\u3059\u3002"):((new Person(a)).addParents(this.relation),this.setupChildren())};
PartnerPanel.prototype.makeChainList=function(){var a=[];this.relation.children.forEach(function(b){var c=new Chain;c.copyChainProperties(b);a.push(c)});return a};PartnerPanel.prototype.makeNewList=function(){var a=[],b={},c=this.childrenView.querySelectorAll("li");this.relation.children.forEach(function(a){b[a.id]=a});Array.prototype.forEach.call(c,function(c,e){c=c.getAttribute("data-id");a.push(b[c])});return a};
PartnerPanel.prototype.reorganizeChildren=function(){var a=this,b=this.makeChainList(),c=this.makeNewList(),d=this.relation.children[0].prevActor,e=[d].concat(c);console.log("prev:");console.log(d);this.relation.children=[];c.forEach(function(c,d){c.copyChainProperties(b[d]);c.prevActor=e[d];console.log("ix:"+d+"|"+c.info+" <-prev:"+c.prevActor.info);a.relation.children.push(c)});$(this.childrenView).listview("refresh")};
PartnerPanel.prototype.setupChildren=function(){var a=this.childrenView;a.textContent=null;this.relation.children.forEach(function(b){var c=document.createElement("span"),d=document.createElement("p"),e=document.createElement("a"),f=document.createElement("li");c.textContent=b.info;d.textContent=b.description;e.appendChild(c);e.appendChild(d);f.appendChild(e);f.setAttribute("data-id",b.id);f.setAttribute("data-icon",!1);a.appendChild(f)});$(a).listview("refresh")};
PartnerPanel.prototype.setupForm=function(){var a=this.panel.querySelector('[name="father"]'),b=this.panel.querySelector('[name="mother"]');a.value=this.relation.father.info;b.value=this.relation.mother.info;$('[name="relationType"]').val([this.relation.type]).checkboxradio("refresh")};PartnerPanel.prototype.open=function(a){this.relation=a;this.setupForm();this.setupChildren();$(this.panel).panel("open")};
var RelationPanel=function(){this.panel=document.getElementById("relationPanel");this.deleteButton=this.panel.querySelector('[name="deleteButton"]');this.to=this.from=null;this.setupEvents()};RelationPanel.prototype.setupEvents=function(){var a=this;$('[name="emotion"]').click(function(){a.deleteRelationship();a.relationship=a.createRelationship();a.resetControls()});this.deleteButton.addEventListener("click",function(){a.deleteRelationship();a.resetControls()});$(this.panel).panel({close:function(){Field.Instance.clearSelection()}})};
RelationPanel.prototype.createRelationship=function(){var a=$('[name="emotion"]:checked'),a=Relationship.create(a.val(),this.from,this.to);a.hit=!0;Field.Instance.addActor(a);return a};RelationPanel.prototype.deleteRelationship=function(){this.relationship&&(this.relationship.eject(),this.relationship=null)};RelationPanel.prototype.resetControls=function(){this.relationship?$(this.deleteButton).removeClass("ui-state-disabled"):$(this.deleteButton).addClass("ui-state-disabled")};
RelationPanel.prototype.setupForm=function(){var a=this.panel.querySelector('[name="from"]'),b=this.panel.querySelector('[name="to"]'),c=$('[name="emotion"]');a.value=this.from.info;b.value=this.to.info;this.relationship?c.val([this.relationship.emotion]).checkboxradio("refresh"):c.removeAttr("checked").checkboxradio("refresh");this.resetControls()};
RelationPanel.prototype.open=function(a,b){(b=void 0===b?null:b)?(this.from=a,this.to=b,this.relationship=null,this.isNew=!0):(this.from=a.person,this.from.hit=!0,this.to=a.other,this.to.hit=!0,this.relationship=a,this.isNew=!1);this.setupForm();$(this.panel).panel("open")};var Actor=function(a,b){this.id=UUID.toString();this.x=void 0===a?0:a;this.y=void 0===b?0:b;this.radius=this.z=0;this.spawnList=[]};
Actor.prototype.reserve=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];this.spawnList=this.spawnList.concat(b)};Actor.prototype.getDistance=function(a){var b=this.x-a.x;a=this.y-a.y;return Math.sqrt(b*b+a*a)};Actor.prototype.getRadian=function(a){return Math.atan2(this.y-a.y,this.x-a.x)};Actor.prototype.getMidpoint=function(a){return new Actor((this.x+a.x)/2,(this.y+a.y)/2)};
Actor.prototype.getInterimPoint=function(a,b,c){var d=this.x-a.x;a=this.y-a.y;b=Math.sqrt(d*d+a*a)*(void 0===b?1:b)/(void 0===c?1:c);d=Math.atan2(a,d);return new Actor(this.x-Math.cos(d)*b,this.y-Math.sin(d)*b)};Actor.prototype.includes=function(a,b,c){a=this.x-a;b=this.y-b;return Math.sqrt(a*a+b*b)<((void 0===c?0:c)|this.radius)};Actor.prototype.isHit=function(a,b){return this.includes(a,b)};Actor.prototype.move=function(a,b){this.x+=a;this.y+=b};Actor.prototype.eject=function(){this.isGone=!0};
Actor.prototype.react=function(){return[]};Actor.prototype.draw=function(a){};$jscomp.global.Object.defineProperties(Actor.prototype,{spawn:{configurable:!0,enumerable:!0,get:function(){var a=this.spawnList;this.spawnList=[];return a}}});var ActorHandle=function(a,b){Actor.call(this,a,b);this.radius=4;this.logicalRadius=2*this.radius;this.prev=this;this.next=this};$jscomp.inherits(ActorHandle,Actor);ActorHandle.prototype.add=function(a){var b=this.next;this.next=a;a.prev=this;a.next=b;b.prev=a};
ActorHandle.prototype.isHit=function(a,b){return this.hit=this.includes(a,b,this.logicalRadius)};
ActorHandle.prototype.isLineHit=function(a,b){if(this.includes(a,b,this.logicalRadius))return!1;for(var c=!1,d=this.nextCp,e=this.next.prevCp,f=this.getDistance(this.next)/this.radius,g=0;g<f;g++){var h=this.getInterimPoint(d,g,f),k=e.getInterimPoint(this.next,g,f),l=d.getInterimPoint(e,g,f),h=h.getInterimPoint(l,g,f),k=l.getInterimPoint(k,g,f),l=h.getInterimPoint(k,g,f),k=l.x-a,l=l.y-b;Math.sqrt(k*k+l*l)<this.radius&&(c=!0)}return c};
ActorHandle.prototype.draw=function(a){this.parent.selected&&(a.save(),a.beginPath(),a.fillStyle=this.hit?"aqua":"gray",a.arc(this.x,this.y,this.radius,0,2*Math.PI,!1),a.fill(),a.restore())};ActorHandle.prototype.drawGuide=function(a){var b=this.prevCp,c=this.nextCp;a.save();a.lineWidth=1;a.strokeStyle="cyan";a.beginPath();a.moveTo(this.x,this.y);a.lineTo(b.x,b.y);a.stroke();a.strokeStyle="lime";a.beginPath();a.moveTo(this.x,this.y);a.lineTo(c.x,c.y);a.stroke();a.restore()};
ActorHandle.prototype.drawSelfCurve=function(a){var b=this.nextCp,c=this.next.prevCp,d=this.getDistance(this.next)/this.radius;a.save();for(var e=0;e<d;e++){var f=this.getInterimPoint(b,e,d),g=c.getInterimPoint(this.next,e,d),h=b.getInterimPoint(c,e,d),f=f.getInterimPoint(h,e,d),g=h.getInterimPoint(g,e,d),g=f.getInterimPoint(g,e,d);a.strokeStyle="pink";a.beginPath();a.arc(g.x,g.y,this.radius,0,2*Math.PI,!1);a.stroke()}a.restore()};
ActorHandle.prototype.drawCurve=function(a){var b=this.nextCp,c=this.next.prevCp;a.beginPath();a.moveTo(this.x,this.y);a.bezierCurveTo(b.x,b.y,c.x,c.y,this.next.x,this.next.y);a.stroke()};
$jscomp.global.Object.defineProperties(ActorHandle.prototype,{list:{configurable:!0,enumerable:!0,get:function(){for(var a=[],b=this.next;b!=this;)a.push(b),b=b.next;return a}},listAll:{configurable:!0,enumerable:!0,get:function(){for(var a=[],b=this.next;;){a.push(b);if(b==this)break;b=b.next}return a}},radian:{configurable:!0,enumerable:!0,get:function(){var a=this.prev,b=this.next;return Math.atan2(b.y-a.y,b.x-a.x)}},prevCp:{configurable:!0,enumerable:!0,get:function(){var a=this.radian,b=.2*this.getDistance(this.prev);
return new Actor(this.x-Math.cos(a)*b,this.y-Math.sin(a)*b)}},nextCp:{configurable:!0,enumerable:!0,get:function(){var a=this.radian,b=.2*this.getDistance(this.next);return new Actor(this.x+Math.cos(a)*b,this.y+Math.sin(a)*b)}}});var Chain=function(){Actor.call(this);this.ry=this.rx=0;this.prevActor=null;this.nextActor=[];this.generation=0};$jscomp.inherits(Chain,Actor);
Chain.prototype.copyChainProperties=function(a){var b=this;this.x=a.x;this.y=a.y;this.rx=a.rx;this.ry=a.ry;this.prevActor=a.prevActor;this.nextActor=a.nextActor;this instanceof Person&&this.nextActor.forEach(function(a){a.generation<b.generation&&(a.prevActor=b)})};Chain.prototype.moveQuickly=function(){this.prevActor&&(this.x=this.ax,this.y=this.ay)};
Chain.prototype.ancestorOccupancy=function(a,b){a=void 0===a?new Occupancy:a;b=void 0===b?0:b;var c=a;a=[];0<b&&(this.listPartner(a),a.forEach(function(a){c.merge(new Occupancy(a))}));this.parents&&(this.parents.father.ancestorOccupancy(c,b+1),this.parents.mother.ancestorOccupancy(c,b+1));return c};
Chain.prototype.descendantOccupancy=function(a,b){var c=a=void 0===a?new Occupancy:a;a=[];if(c.isDone(this))return c;c.merge(new Occupancy(this));this.listPartner(a);a.forEach(function(a){a.descendantOccupancy(c)});return c};Chain.prototype.listOccupancy=function(a){this.relationList.forEach(function(a){});return{left:1,right:1}};
Chain.prototype.leave=function(a,b){this.rest&&a.rest&&(b=a.x-this.x,this.prevActor==a?(0>b?this.rx++:0<b&&this.rx--,8<Math.abs(this.rx)&&(console.log("**error** #leave.this/rx:"+this.rx),this.rx%=8)):a.prevActor==this?0>b?a.rx--:0<b&&a.rx++:(console.log("**error** #leave.else"),console.log(this)))};
Chain.prototype.assignActor=function(a,b,c){b=void 0===b?0:b;c=void 0===c?0:c;this.prevActor!=a&&a.prevActor!=this&&(console.log("[assignActor]"),a.prevActor=this,a.x=this.x+b,a.y=this.y,a.rx=b,a.ry=c,a.generation=this.generation,0>c?a.generation--:0<c&&a.generation++,console.log(this.info+":G"+this.generation+" -> "+a.info+":G"+a.generation),this.nextActor.push(a))};
Chain.prototype.addActor=function(a,b,c){c=void 0===c?0:c;console.log("Chain#addActor");var d=this.getNextPartner();a.prevActor=this;a.rx=b;a.ry=c;a.x=this.x;a.y=this.y;if(d){var e=this.nextActor.indexOf(d);console.log(a.info+" -> "+d.info);d.prevActor=a;d.rx=b;d.ry=c;a.rx=d.rx;a.ry=d.ry;a.nextActor.push(d);this.nextActor.splice(e,1)}a.generation=this.generation;0>c?a.generation--:0<c&&a.generation++;console.log(this.info+":G"+this.generation+" -> "+a.info+":G"+a.generation);this.nextActor.push(a)};
Chain.prototype.insertActor=function(a,b,c){c=void 0===c?0:c;b=this.prevActor;var d=b.nextActor.indexOf(this);b.nextActor.splice(d,1);b.nextActor.push(a);a.prevActor=b;a.x=b.x;a.y=b.y;a.rx=this.rx;a.ry=this.ry;a.generation=this.generation;0>c?a.generation--:0<c&&a.generation++;a.nextActor.push(this);this.prevActor=a};Chain.prototype.reassignActor=function(a,b,c){c=void 0===c?0:c;this.prevActor==a&&(this.rx=-b,this.ry=-c);a.prevActor==this&&(a.rx=b,a.ry=c)};
Chain.prototype.getPrevPartner=function(){var a=this.prevActor;return a instanceof Person&&a.generation==this.generation&&!this.isSibling(a)?a:null};Chain.prototype.getNextPartner=function(){var a=this,b=null;this.nextActor.forEach(function(c){c.generation!=a.generation||a.isSibling(c)||(b=c)});return b};
Chain.prototype.addPartner=function(a){console.log("Chain#addPartner:"+this.info);var b=this.getPrevPartner();this.getNextPartner();var c=!1,d=this.isMale?2:-2;b&&(c=this.isMale?this.x<b.x:b.x<this.x);c?(console.log("addToPrev"),b.addActor(a,-d)):(console.log("prev\u306a\u3057"),this.addActor(a,d))};
$jscomp.global.Object.defineProperties(Chain.prototype,{ax:{configurable:!0,enumerable:!0,get:function(){return this.prevActor?this.prevActor.ax+this.rx:this.x}},ay:{configurable:!0,enumerable:!0,get:function(){return this.prevActor?this.prevActor.ay+this.ry:this.y}},rest:{configurable:!0,enumerable:!0,get:function(){return this.prevActor?this.x==this.ax&&this.y==this.ay:!0}}});var Ties=function(a){Chain.call(this);this.gender=a;this.parents=null;this.relationList=[]};$jscomp.inherits(Ties,Chain);
Ties.prototype.attributeChanged=function(){};Ties.prototype.isSibling=function(a){return this.parents&&a.parents?this.parents==a.parents:!1};Ties.prototype.addParents=function(a){console.log("Ties#addParents");a.leftSide.addPartner(a);a.addChild(this);this.reserve(a,a.leftSide,a.rightSide)};Ties.prototype.getOrder=function(a){var b=this,c=-1;this.relationList.forEach(function(d,e){b.isMale?d.mother==a&&(c=e):d.father==a&&(c=e)});return c};
Ties.prototype.listPartner=function(a){if(-1==a.indexOf(this)){var b=this.partnerList;this.isMale?a.push(this):b.reverse();b.forEach(function(b){b.listPartner(a)});this.isMale||-1!=a.indexOf(this)||a.push(this)}};Ties.prototype.hasRelation=function(a){return-1!=this.relationList.indexOf(a)};
Ties.prototype.addPartner=function(a){if(this.hasRelation(a))return this.relationList.length;console.log("Ties#addPartner");var b=this.relationList.unshift(a),c=a.getPartner(this),d=c.hasRelation(a);this.relationList.forEach(function(a,c){a.order=c;a.orderMax=b});d||(1<b&&(this.relationList[1].type="d"),Chain.prototype.addPartner.call(this,c));c.addPartner(a);return b};Ties.prototype.remove=function(){this.parents&&this.parents.removeChild(this);this.eject()};
Ties.prototype.move=function(){if(!this.prevActor)return!1;var a=this.ax,b=this.ay,c=a-this.x,d=b-this.y,e=Math.abs(c),f=Math.abs(d);if(0==e&&0==f)return!1;e<=Ties.MOVING_STEP?this.x=a:0>c?this.x-=Ties.MOVING_STEP:0<c&&(this.x+=Ties.MOVING_STEP);f<=Ties.MOVING_STEP?this.y=b:0>d?this.y-=Ties.MOVING_STEP:0<d&&(this.y+=Ties.MOVING_STEP);return!0};
$jscomp.global.Object.defineProperties(Ties.prototype,{gender:{configurable:!0,enumerable:!0,get:function(){return this._gender},set:function(a){this._gender=a;this.attributeChanged()}},isMale:{configurable:!0,enumerable:!0,get:function(){return"m"==this.gender}},mother:{configurable:!0,enumerable:!0,get:function(){return this.parents?this.parents.mother:null}},father:{configurable:!0,enumerable:!0,get:function(){return this.parents?this.parents.father:null}},numOfPartner:{configurable:!0,enumerable:!0,
get:function(){return this.relationList.length}},partnerList:{configurable:!0,enumerable:!0,get:function(){var a=this,b=[];this.relationList.forEach(function(c){b.push(c.getPartner(a))});return b}},hasChild:{configurable:!0,enumerable:!0,get:function(){var a=!1;this.relationList.forEach(function(b){0<b.children.length&&(a=!0)});return a}}});Ties.MOVING_STEP=.9;var ChainRoot=function(){Chain.call(this);this.id="root";this.radius=5};$jscomp.inherits(ChainRoot,Chain);
ChainRoot.prototype.draw=function(a){a.save();a.beginPath();a.arc(0,0,this.radius,0,2*Math.PI,!1);a.fillStyle="green";a.fill();a.restore()};$jscomp.global.Object.defineProperties(ChainRoot.prototype,{info:{configurable:!0,enumerable:!0,get:function(){return this.id+"("+this.x+","+this.y+")"}}});var Controller=function(a){this.keys={};this.point={};this.touch=!1;this.init(void 0===a?!1:a);Controller.Instance=this};
Controller.prototype.init=function(a){a||window.addEventListener("contextmenu",function(a){a.preventDefault()});this.initKeys();this.initPointingDevice()};Controller.prototype.initKeys=function(){var a=this;window.addEventListener("keydown",function(b){b.key?a.keys[b.key]=!0:a.keys["k"+b.keyCode]=!0});window.addEventListener("keyup",function(b){b.key?delete a.keys[b.key]:delete a.keys["k"+b.keyCode]})};
Controller.prototype.initPointingDevice=function(){var a=this,b=document.getElementById("canvas"),c=function(){a.touch=!1;a.point=null};b.addEventListener("mousedown",function(b){a.touch=!0;a.point=FlexibleView.Instance.convert(b.clientX,b.clientY)});b.addEventListener("mousemove",function(b){a.touch&&(a.point=FlexibleView.Instance.convert(b.clientX,b.clientY))});b.addEventListener("mouseup",function(){return c()});b.addEventListener("mouseleave",function(){return c()});b.addEventListener("touchstart",
function(b){var c=b.touches[0];a.touch=!0;a.point=FlexibleView.Instance.convert(c.pageX,c.pageY);b.preventDefault()});b.addEventListener("touchmove",function(b){b=b.touches[0];a.touch=!0;a.point=FlexibleView.Instance.convert(b.pageX,b.pageY)});b.addEventListener("touchend",function(){return c()})};var Description=function(a,b,c,d){d=void 0===d?0:d;Actor.call(this,0,0,0);this.person=a;this.dx=c;this.dy=d;this.text=b};$jscomp.inherits(Description,Actor);
Description.prototype.calculate=function(a){var b=Field.Instance.spacing,c=Field.Instance.fontSize,d=0,e=0,f=!0;this.lines.reverse().forEach(function(c){var g=a.measureText(c);d=Math.max(d,g.width/b);f&&0==c.length||(f=!1,e++)});this.width=d;this.height=e*c/b;this.hW=d/2;this.hH=this.height/2};Description.prototype.isHit=function(a,b){return this.hit=!1};
Description.prototype.drawFrame=function(a){if(this.selected)this.strokeStyle="navy",a.lineWidth=5;else if(this.hit)this.strokeStyle="aqua",a.lineWidth=5;else return;a.strokeStyle=this.strokeStyle;var b=Field.Instance.spacing,c=-this.hH*b,d=-this.hW*b,e=this.width*b,b=this.height*b;a.strokeRect(d,c,e,b);a.fillStyle="rgba(0, 255, 255, .1)";a.fillRect(d,c,e,b)};
Description.prototype.drawLine=function(a){if(this.selected||this.hit){var b=Field.Instance.spacing,c=this.getRadian(this.person),d=-this.x+this.person.x+.5*Math.cos(c),c=-this.y+this.person.y+.5*Math.sin(c);a.beginPath();a.moveTo(d*b,c*b);a.lineTo(0*b,0*b);a.stroke()}};Description.prototype.drawText=function(a){var b=Field.Instance.spacing,c=Field.Instance.fontSize,d=-this.hH*b+c/2,e=-this.hW*b;a.fillStyle="black";this.lines.forEach(function(b){a.fillText(b,e,d);d+=c})};
Description.prototype.draw=function(a){this.calculate(a);var b=Field.Instance.spacing,c=this.x*b,b=this.y*b;a.save();a.translate(c,b);this.drawFrame(a);this.drawLine(a);this.drawText(a);a.restore()};
$jscomp.global.Object.defineProperties(Description.prototype,{x:{configurable:!0,enumerable:!0,get:function(){return this.person.x+this.dx},set:function(a){this.person&&(this.dx=a-this.person.x)}},y:{configurable:!0,enumerable:!0,get:function(){return this.person.y+this.dy},set:function(a){this.person&&(this.dy=a-this.person.y)}},lines:{configurable:!0,enumerable:!0,get:function(){return this.text.split(/\r\n|\r|\n/)}}});
var EnclosingLine=function(){ActorHandle.call(this,100,100);this.parent=this;this.addHandle(200,100);this.addHandle(200,200);this.addHandle(100,200);this.addHandle(50,150);this.addHandle(50,120);this.spawnList=this.list};$jscomp.inherits(EnclosingLine,ActorHandle);EnclosingLine.prototype.addHandle=function(a,b){a=new ActorHandle(a,b);a.parent=this;this.add(a)};
EnclosingLine.prototype.isHit=function(a,b){var c=this,d=ActorHandle.prototype.isHit.call(this,a,b);this.hit=d;this.lineHit=!1;this.listAll.forEach(function(d){d.isLineHit(a,b)&&(c.lineHit=!0)});return d|this.lineHit};EnclosingLine.prototype.drawLine=function(a){a.lineWidth=.5;a.strokeStyle="lightglay";a.beginPath();a.moveTo(this.x,this.y);this.listAll.forEach(function(b){a.lineTo(b.x,b.y)});a.stroke()};
EnclosingLine.prototype.drawAll=function(a){this.selected?(a.lineWidth=2,a.strokeStyle="navy"):this.lineHit?(a.lineWidth=2,a.strokeStyle="aqua"):a.lineWidth=1;this.listAll.forEach(function(b){b.drawCurve(a)})};EnclosingLine.prototype.draw=function(a){ActorHandle.prototype.draw.call(this,a);a.save();this.drawAll(a);a.restore()};
var Field=function(a,b){this.width=a;this.height=b;this.view=new FlexibleView(a,b);this.ty=this.tx=0;this.focus=null;this.targetList=[];this.actorList=[];this.dirty=!1;this.setupEvents();this.maxGeneration=this.minGeneration=0;Field.Instance=this};Field.prototype.createPair=function(a,b){var c=null;this.pairList.forEach(function(d){d.isPair(a,b)&&(c=d)});null==c&&(c=new Relation(a,b));return c};
Field.prototype.getRelationship=function(a,b){var c=null;this.actorList.forEach(function(d){!c&&d instanceof Relationship&&(d.person==a&&d.other==b||d.person==b&&d.other==a)&&(c=d)});return c};Field.prototype.allowTarget=function(a){return a instanceof Person||a instanceof Relation||a instanceof Relationship||a instanceof EnclosingLine};
Field.prototype.setupEvents=function(){var a=this,b=this.view.view,c=Controller.Instance.keys,d=null;b.addEventListener("mousedown",function(b){d=a.view.convert(b.clientX,b.clientY);b=a.scan(d.x,d.y);c.Control||c.Shift||c.k16||c.k17||(a.targetList=[]);a.allowTarget(b)&&a.targetList.push(b);if(b instanceof Description||b instanceof ActorHandle)a.hold=b});b.addEventListener("mouseup",function(b){a.dirty=!0;a.hold=null});b.addEventListener("mousemove",function(b){b=a.view.convert(b.clientX,b.clientY);
if(a.hold){var c=a.spacing;a.hold.move((b.x-d.x)/c,(b.y-d.y)/c);d=b}else a.scan(b.x,b.y)})};Field.prototype.setFocus=function(a){this.focus=a;this.dirty=!0};Field.prototype.addActor=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];var d=this;b.forEach(function(a){-1==d.actorList.indexOf(a)&&(d.actorList.push(a),a instanceof Person&&(d.minGeneration=Math.min(d.minGeneration,a.generation),d.maxGeneration=Math.max(d.maxGeneration,a.generation)))});this.dirty=!0};
Field.prototype.scan=function(a,b){var c=null,d=a-this.tx,e=b-this.ty;this.actorList.forEach(function(a){a.hit=!1;c||a.isHit(d,e)&&(c=a)});return c};Field.prototype.clearSelection=function(){this.scan(Number.MAX_VALUE,Number.MAX_VALUE);this.targetList=[]};
Field.prototype.arrange=function(){var a=this;if(this.dirty){console.log("[dirty]"+this.actorList.length);this.dirty=!1;var b=0,c=0,d=0,e=0,f=[];this.focus.x=0;this.focus.y=0;Tally.reset();this.actorList.forEach(function(a){a instanceof Relation&&f.push(a)});this.personList.forEach(function(f){var g=f.move(),h=f.x;f=f.y;b=Math.min(b,h);c=Math.min(c,f);d=Math.max(d,h);e=Math.max(e,f);g&&(a.dirty=!0)});this.dirty||f.forEach(function(b){b.reassign()&&(a.dirty=!0)});var g=this.spacing,h=b*g,k=c*g,l=(this.height-
(e*g-k))/2;this.tx=(this.width-(d*g-h))/2-h;this.ty=l-k}};Field.prototype.choiceActor=function(){var a=this,b=[].concat(this.actorList);this.actorList=[];b.forEach(function(c){c.isGone||(a.actorList.push(c),c.spawn.forEach(function(c){-1==b.indexOf()&&a.addActor(c)}))});this.actorList.length!=b.length&&(this.dirty=!0);this.actorList.sort(function(a,b){return a.z-b.z})};
Field.prototype.drawGrid=function(a){if(this.showGrid){var b=this.width/2,c=this.height/2,d=this.spacing,e=-c,f=-b;a.save();a.lineWidth=.2;a.strokeStyle="aqua";a.translate(b,c);for(var g=0;g<b;g+=d)a.beginPath(),a.moveTo(g,e),a.lineTo(g,c),a.stroke(),0<g&&(a.beginPath(),a.moveTo(-g,e),a.lineTo(-g,c),a.stroke());for(e=0;e<c;e+=d)a.beginPath(),a.moveTo(f,e),a.lineTo(b,e),a.stroke(),0<e&&(a.beginPath(),a.moveTo(f,-e),a.lineTo(b,-e),a.stroke());a.restore()}};
Field.prototype.draw=function(){var a=this,b=this.view.ctx,c=this.fontSize;this.view.clear();this.choiceActor();this.drawGrid(b);b.save();b.font=c+"px 'Times New Roman'";b.textBaseline="middle";b.translate(this.tx,this.ty);this.actorList.forEach(function(d){d.fontSize=c;d.selected=-1!=a.targetList.indexOf(d);d.draw(b)});b.restore()};
$jscomp.global.Object.defineProperties(Field.prototype,{showGrid:{configurable:!0,enumerable:!0,get:function(){return document.querySelector('[name="grid"]').checked}},showName:{configurable:!0,enumerable:!0,get:function(){return document.querySelector('[name="showName"]').checked}},spacing:{configurable:!0,enumerable:!0,get:function(){var a=document.querySelector('[name="gridSpacing"]');(a=parseFloat(a.value))||(a=80);return a}},fontSize:{configurable:!0,enumerable:!0,get:function(){var a=document.querySelector('[name="fontSize"]');
(a=parseFloat(a.value))||(a=12);return a}},lineStyle:{configurable:!0,enumerable:!0,get:function(){return"gray"}},personList:{configurable:!0,enumerable:!0,get:function(){var a=[];this.actorList.forEach(function(b){b instanceof Person&&a.push(b)});return a}},pairList:{configurable:!0,enumerable:!0,get:function(){var a=[];this.actorList.forEach(function(b){b instanceof Relation&&a.push(b)});return a}},numOfGeneration:{configurable:!0,enumerable:!0,get:function(){return this.maxGeneration-this.minGeneration+
1}}});Field.MAX_GENERATION=3;var FlexibleView=function(a,b){this.view=document.getElementById("view");this.canvas=document.getElementById("canvas");this.ctx=this.canvas.getContext("2d");this.scale=1;this.init();this.setSize(a,b);FlexibleView.Instance=this};FlexibleView.prototype.setSize=function(a,b){this.width=a;this.height=b;this.canvas.width=a;this.canvas.height=b;this.resize()};
FlexibleView.prototype.init=function(){var a=this,b=document.querySelector('[data-role="header"]'),c=document.querySelector('[data-role="footer"]');this.headerHeight=b?b.offsetHeight:0;this.footerHeight=c?c.offsetHeight:0;this.margin=this.headerHeight+this.footerHeight;window.addEventListener("resize",function(){a.resize()});window.addEventListener("keydown",function(){view.classList.contains("addicting")||view.classList.add("addicting")});window.addEventListener("mousemove",function(){view.classList.remove("addicting")})};
FlexibleView.prototype.resize=function(){var a=document.body.clientWidth/this.width,b=(window.innerHeight-this.margin)/this.height;this.scale=b<a?b:a;this.view.setAttribute("style",["width:"+this.width+"px","height:"+this.height+"px","transform: scale("+this.scale+")"].join(";"))};FlexibleView.prototype.convert=function(a,b){return{x:a/this.scale,y:(b-this.headerHeight)/this.scale}};FlexibleView.prototype.clear=function(){this.ctx.clearRect(0,0,this.width,this.height)};
var GenoCalendar=function(a){this.day=this.month=this.year=null;a&&this.setupDate(new String(a))};GenoCalendar.prototype.setupDate=function(a){var b=a.split(/[-/]/g);a=(new Date).getFullYear()+1;var c=parseInt(b[0]);Number.isFinite(c)?c+1900<a&&(c+=1900):c=null;this.year=c;if(1<b.length){a=parseInt(b[1]);if(2<b.length)b=new Date(c,a-1,parseInt(b[2])),b.getFullYear(),a=b.getMonth()+1,this.day=b=b.getDate();else if(0>a||12<a)a=1;this.month=a}};
GenoCalendar.prototype.toString=function(){var a=[];this.year&&(a.push(this.year),this.month&&(a.push(this.month),this.day&&a.push(this.day)));return a.join("-")};
$jscomp.global.Object.defineProperties(GenoCalendar.prototype,{age:{configurable:!0,enumerable:!0,get:function(){if(!this.year)return null;var a=new Date,b=a.getFullYear();if(!this.month)return b-this.year;var c=a.getMonth()+1;if(!this.dd)return Math.floor((100*b+c-(100*this.year+this.month))/100);a=a.getDate();return Math.floor((1E4*b+100*c+a-(1E4*this.year+100*this.month+this.day))/1E4)}}});
var Occupancy=function(a,b,c,d,e){a=void 0===a?null:a;b=void 0===b?Number.MAX_SAFE_INTEGER:b;c=void 0===c?Number.MAX_SAFE_INTEGER:c;d=void 0===d?Number.MIN_SAFE_INTEGER:d;e=void 0===e?Number.MIN_SAFE_INTEGER:e;this.top=b;this.left=c;this.right=d;this.bottom=e;this.personList=[];a&&(this.right=this.left=b=a.ax,this.personList.push(a))};Occupancy.prototype.isDone=function(a){return-1!=this.personList.indexOf(a)};
Occupancy.prototype.merge=function(a){this.top=Math.min(this.top,a.top);this.left=Math.min(this.left,a.left);this.right=Math.max(this.right,a.right);this.bottom=Math.max(this.bottom,a.bottom);this.personList=this.personList.concat(a.personList)};$jscomp.global.Object.defineProperties(Occupancy.prototype,{width:{configurable:!0,enumerable:!0,get:function(){return this.right-this.left}}});
var Person=function(a){Ties.call(this,void 0===a?"":a);this.name=AlphabeticalTally.increment();this._description=null;this.attr=this.dod=this.dob="";this.principal=!1};$jscomp.inherits(Person,Ties);Person.MOVING_STEP=Ties.MOVING_STEP;Person.prototype.attributeChanged=function(){this.symbol=this.isMale?new MaleSymbol(this):new FemaleSymbol(this)};
Person.prototype.scanAll=function(a,b){b=void 0===b?0:b;var c=this;-1===a.indexOf(this)&&(this.depth=b,this.touched=this.fixed=!1,a.push(this),this.mother&&this.mother.scanAll(a,b-1),this.relationList.forEach(function(d){d.getPartner(c).scanAll(a,b);d.children.forEach(function(c){c.scanAll(a,b+1)})}))};
Person.prototype.calculateChildren=function(a){var b=a.children,c=1==b.length,d=a.allChildren,e=a.rect.center-2*(c?0:d.length-1)/2,f=this.y+2;b.forEach(function(a){var b=2*a.numOfPartner;a.isMale||c||(e+=b);a.x=e;a.y=f;a.calculate();a.isMale&&(e+=b);e+=2})};
Person.prototype.calculate=function(){var a=this;if(!this.fixed){var b=[],c=[];this.listPartner(b);var d=2*-b.indexOf(this);b.forEach(function(b){b==a||b.fixed||(b.x=a.x+d,b.y=a.y);b.count=Tally.increment();b.fixed=!0;d+=2});b.forEach(function(a){a.relationList.forEach(function(a){-1==c.indexOf(a)&&c.push(a)});a.mother&&!a.mother.fixed&&(a.mother.x=a.x+1,a.mother.y=a.y-2,a.mother.calculate())});this.relationList.forEach(function(b,c){a.calculateChildren(b)})}};
Person.prototype.touch=function(a){var b=this.x-a.x;a=this.y-a.y;1>=Math.sqrt(b*b+a*a)&&(this.touched=!0);return this.touched};Person.prototype.isHit=function(a,b){var c=Field.Instance.spacing;return this.hit=this.symbol.isHit(a/c,b/c)};Person.prototype.drawSymbol=function(a){this.selected?(this.strokeStyle="navy",a.lineWidth=5):this.hit?(this.strokeStyle="aqua",a.lineWidth=5):(this.strokeStyle="black",a.lineWidth=3);this.touched&&(this.strokeStyle="red");this.symbol.draw(a)};
Person.prototype.drawAncestorOccupancy=function(a){if(this.parents){var b=Field.Instance.spacing,c=this.ancestorOccupancy(new Occupancy(this)),d=c.left+.1,c=c.right-.1,e=(this.y-.1)*b;a.strokeStyle="purple";a.beginPath();a.moveTo(d*b,e);a.lineTo(c*b,e);a.stroke()}};Person.prototype.drawDescendantOccupancy=function(a){var b=Field.Instance.spacing,c=this.descendantOccupancy(),d=c.left+.2,c=c.right-.2,e=(this.y+.1)*b;a.lineWidth=3;a.strokeStyle="green";a.beginPath();a.moveTo(d*b,e);a.lineTo(c*b,e);a.stroke()};
Person.prototype.drawOccupancy=function(a){this.drawAncestorOccupancy(a)};Person.prototype.drawChain=function(a){if(this.prevActor){var b=Field.Instance.spacing,c=this.prevActor,d=this.isSibling(c),e=c.x-this.x,c=c.y-this.y,f=0,g=0;0>e?(c-=.2,f-=.1*b,g-=.2*b):(c+=.2,f+=.1*b,g+=.2*b);e*=b;c*=b;a.lineWidth=.6;a.strokeStyle="lime";a.beginPath();a.arc(e,c,4,0,2*Math.PI,!1);a.moveTo(e,c);d?a.quadraticCurveTo(e+(f-e)/2,c-.5*b,f,g):a.lineTo(f,g);a.stroke()}};
Person.prototype.draw=function(a){var b=Field.Instance.spacing,c=this.x*b,b=this.y*b;a.save();this.drawOccupancy(a);a.translate(c,b);this.drawChain(a);this.drawSymbol(a);a.restore()};Person.createFromEntity=function(a){var b=new Person;Person.Properties.forEach(function(c){var d=a[c];d&&(b[c]=d)});return b};
$jscomp.global.Object.defineProperties(Person.prototype,{description:{configurable:!0,enumerable:!0,get:function(){return null==this._description?"":this._description.text},set:function(a){null==a||0==a.length?null!=this._description&&(this._description.eject(),this._description=null):null!=this._description?this._description.text=a:(this._description=new Description(this,a,1),this.spawnList.push(this._description))}},dx:{configurable:!0,enumerable:!0,get:function(){return null==this._description?
0:this._description.dx},set:function(a){null!=this._description&&(this._description.dx=a)}},dy:{configurable:!0,enumerable:!0,get:function(){return null==this._description?0:this._description.dy},set:function(a){null!=this._description&&(this._description.dy=a)}},age:{configurable:!0,enumerable:!0,get:function(){return(new GenoCalendar(this.dob)).age}},info:{configurable:!0,enumerable:!0,get:function(){var a=this.name,b=this.age;b&&(a+="("+b+")");return a}},radius:{configurable:!0,enumerable:!0,get:function(){return Field.Instance.spacing/
2}}});Person.Properties="id name description dx dy gender dob dod attr".split(" ");var Relation=function(a,b){Actor.call(this);a.isMale?(this.leftSide=a,this.rightSide=b):(this.leftSide=b,this.rightSide=a);this.type="m";this.children=[];this.hit=!1;this.initImage()};$jscomp.inherits(Relation,Actor);Relation.prototype.initImage=function(){this.divorceImage=new Image;this.divorceImage.src="img/ralation.divorce.png";this.separateImage=new Image;this.separateImage.src="img/ralation.separate.png"};
Relation.prototype.isPair=function(a,b){return this.leftSide==a&&this.rightSide==b||this.leftSide==b&&this.rightSide==a?!0:!1};Relation.prototype.getPartner=function(a){return a==this.father?this.mother:this.father};
Relation.prototype.addChild=function(a){console.log("Relation#addChild");var b=this.children.length;a.parents=this;this.children.push(a);this.reserve(a);0<b?(b=this.children[b-1],b.isMale?b.assignActor(a,2*(b.numOfPartner+1)):b.assignActor(a,2)):a.prevActor?(console.log("child.assign father"),a.assignActor(this.father,0,-2)):(console.log("father.assign child"),this.father.assignActor(a,0,2));this.reassign()};
Relation.prototype.reassignOccupancy=function(){if(!(this.father.parents&&this.mother.parents&&this.leftSide.rest&&this.rightSide.rest))return!1;var a=this.leftSide.ancestorOccupancy(new Occupancy(this.leftSide));return 0!=this.rightSide.ancestorOccupancy(new Occupancy(this.rightSide)).left-a.right-2?(this.leftSide.leave(this.rightSide),!0):!1};
Relation.prototype.reassignChildren=function(){var a=!1;if(0==this.children.length)return a;var b=0;this.children.forEach(function(c,d){var e=c.descendantOccupancy();c.isMale?(0<d&&c.rx!=b&&(c.rx=b,a=!0),b=2+e.width):(e=e.width+b,0<d&&c.rx!=e&&(c.rx=e,a=!0),b=2)});return a};
Relation.prototype.reassign=function(){if(this.reassignOccupancy()||this.reassignChildren())return!0;if(0==this.children.length)return!1;for(var a=!1,b=this.firstChild,c=this.lastChild,d=c.prevActor.x+c.rx,e=d;c!=b;)c=c.prevActor,e=c.prevActor.x+c.rx;d=(d-e)/2;b==this.leftSide.prevActor||b==this.rightSide.prevActor?(d=d-this.rect.center+this.leftSide.x,b.rest&&this.leftSide.rx!=d&&(this.leftSide.rx=d,a=!0)):(d=this.rect.center-b.prevActor.x-d,b.prevActor.rest&&b.rx!=d&&(b.rx=d,a=!0));return a};
Relation.prototype.removeChild=function(a){var b=this.children.indexOf(a);this.children.splice(b,1);a.eject()};Relation.prototype.isHit=function(a,b){var c=Field.Instance.spacing;a/=c;b/=c;c=this.rect;this.hit=!1;c.left<=a&&a<=c.right&&c.top<=b&&b<=c.bottom&&(this.hit=!0);return this.hit};
Relation.prototype.drawOccupancy=function(a){var b=this.occupancy;if(0!=b.left){var c=Field.Instance.spacing,d=c/2,e=this.rect,f=e.center-b.left*d,e=e.bottom,b=(b.left+b.right)*d;a.strokeStyle="green";a.strokeRect(f,e,b,c)}};
Relation.prototype.drawNormal=function(a){var b=Field.Instance.spacing,c=this.rect,d=c.top*b,e=c.left*b,f=c.right*b,g=c.bottom*b,b=c.center*b;a.beginPath();a.moveTo(e,d);a.lineTo(e,g);a.lineTo(f,g);a.lineTo(f,d);a.stroke();a.translate(-8,-8);"d"==this.type?a.drawImage(this.divorceImage,b,g):"s"==this.type&&a.drawImage(this.separateImage,b,g)};Relation.prototype.drawText=function(a){var b=Field.Instance.spacing;a.fillText(this.fatherOrder+"/"+this.motherOrder,this.rect.center*b,this.top*b)};
Relation.prototype.drawChildLine=function(a){if(0!=this.children.length){var b=Field.Instance.spacing,c=(this.y+.25)*b,d=!0,e=null,f=this.rect,g=f.center*b,f=f.bottom*b;a.strokeStyle=Field.Instance.lineStyle;a.beginPath();a.moveTo(g,f);a.lineTo(g,c);this.children.forEach(function(f){var g=f.x*b,h=(f.y-.5)*b;d&&(a.lineTo(g,c),a.stroke(),d=!1);a.beginPath();a.moveTo(g,c);a.lineTo(g,h);a.stroke();e=f});a.beginPath();a.moveTo(g,c);a.lineTo(e.x*b,c);a.stroke()}};
Relation.prototype.draw=function(a,b){a.save();this.drawChildLine(a);this.hit?(a.strokeStyle="aqua",a.lineWidth=5,this.drawNormal(a),this.drawText(a)):(a.strokeStyle=Field.Instance.lineStyle,this.drawNormal(a));a.restore()};Relation.prototype.createEntity=function(){return{id:this.id}};
$jscomp.global.Object.defineProperties(Relation.prototype,{father:{configurable:!0,enumerable:!0,get:function(){return this.leftSide.isMale?this.leftSide:this.rightSide}},mother:{configurable:!0,enumerable:!0,get:function(){return this.leftSide.isMale?this.rightSide:this.leftSide}},x:{configurable:!0,enumerable:!0,get:function(){return this.left+Math.abs(this.leftSide.x-this.rightSide.x)/2}},y:{configurable:!0,enumerable:!0,get:function(){return this.leftSide.y+1}},top:{configurable:!0,enumerable:!0,
get:function(){return this.leftSide.y+.5}},left:{configurable:!0,enumerable:!0,get:function(){return Math.min(this.leftSide.x,this.rightSide.x)}},partnerOrder:{configurable:!0,enumerable:!0,get:function(){return Math.max(this.father.partnerOrder,this.mother.partnerOrder)}},fatherOrder:{configurable:!0,enumerable:!0,get:function(){return this.mother.getOrder(this.father)}},motherOrder:{configurable:!0,enumerable:!0,get:function(){return this.father.getOrder(this.mother)}},order:{configurable:!0,enumerable:!0,
get:function(){return this.relationOrder},set:function(a){this.relationOrder=this.z=a}},firstChild:{configurable:!0,enumerable:!0,get:function(){return this.children[0]}},lastChild:{configurable:!0,enumerable:!0,get:function(){return this.children[this.children.length-1]}},rect:{configurable:!0,enumerable:!0,get:function(){var a=this.father,b=this.mother,c=a.y+.5,d=Math.min(a.x,b.x),e=Math.abs(a.x-b.x),f=.25+.1*(this.order-1);this.x=a=1==this.father.numOfPartner&&1==this.mother.numOfPartner?this.father.x+
(this.mother.x-this.father.x)/2:this.fatherOrder<this.motherOrder?b.x-1:a.x+1;this.y=c+f;return{top:c,left:d,right:d+e,bottom:c+f,center:a,width:e,height:f}}},allChildren:{configurable:!0,enumerable:!0,get:function(){var a=[];this.children.forEach(function(b){var c=b.partnerList;b.isMale?(a.push(b),a=a.concat(c)):(a=a.concat(c),a.push(b))});return a}},occupancy:{configurable:!0,enumerable:!0,get:function(){var a=this.allChildren.length;if(1==this.children.length){var b=2*a-1;this.children[0].isMale?
a=1:(a=b,b=1)}else b=a;return{left:a,right:b}}}});var GenoSymbol=function(a){this.person=a};GenoSymbol.prototype.drawSymbol=function(a){var b=2*this.radius;a.strokeRect(-this.radius,-this.radius,b,b);if(this.person.principal){var b=this.ir,c=2*b;a.strokeRect(-b,-b,c,c)}};GenoSymbol.prototype.drawCross=function(a){var b=-this.radius,c=-this.radius,d=this.radius,e=this.radius;a.beginPath();a.moveTo(c,b);a.lineTo(d,e);a.stroke();a.beginPath();a.moveTo(d,b);a.lineTo(c,e);a.stroke()};
GenoSymbol.prototype.drawYears=function(a){new GenoCalendar(this.person.dob);var b=new GenoCalendar(null);var c=new GenoCalendar(this.person.dod);b=[b.year,c.year].join("-");1>=b.length||a.fillText(b,0,-(this.textHh+this.radius))};GenoSymbol.prototype.drawAge=function(a){var b=this.person.age;b&&(a.strokeText(b,0,0),a.fillText(b,0,0))};GenoSymbol.prototype.drawName=function(a){Field.Instance.showName&&a.fillText(this.person.name,0,this.textHh+this.radius)};
GenoSymbol.prototype.resetProperties=function(){this.radius=this.person.radius;this.width=2*this.radius;this.ir=.8*this.radius;this.fontSize=this.person.fontSize;this.textMargin=.2*this.fontSize;this.textHh=this.fontSize/2+this.textMargin};
GenoSymbol.prototype.draw=function(a){this.resetProperties();a.save();a.strokeStyle=this.person.strokeStyle;a.textAlign="center";this.drawSymbol(a);this.person.dod&&(a.lineWidth=1,this.drawCross(a));a.lineWidth=1;a.strokeStyle="black";a.fillStyle="black";this.drawAge(a);this.drawYears(a);this.drawName(a);a.restore()};var FemaleSymbol=function(a){GenoSymbol.apply(this,arguments)};$jscomp.inherits(FemaleSymbol,GenoSymbol);
FemaleSymbol.prototype.isHit=function(a,b){var c=this.person;a=c.x-a;b=c.y-b;return.5>=Math.sqrt(a*a+b*b)};FemaleSymbol.prototype.drawSymbol=function(a){a.beginPath();a.arc(0,0,this.radius,0,2*Math.PI,!1);a.stroke();this.person.principal&&(a.beginPath(),a.arc(0,0,this.ir,0,2*Math.PI,!1),a.stroke())};
FemaleSymbol.prototype.drawCross=function(a){var b=Math.PI/2,c=b/2,d=Math.cos(c+b)*this.radius,b=-Math.sin(c+b)*this.radius,e=Math.sin(c)*this.radius,c=Math.cos(-c)*this.radius;a.beginPath();a.moveTo(b,d);a.lineTo(e,c);a.stroke();a.beginPath();a.moveTo(e,d);a.lineTo(b,c);a.stroke()};var MaleSymbol=function(a){GenoSymbol.apply(this,arguments)};$jscomp.inherits(MaleSymbol,GenoSymbol);MaleSymbol.prototype.isHit=function(a,b){var c=this.person;b=c.y-b;return.5>=Math.abs(c.x-a)&&.5>=Math.abs(b)};
var Relationship=function(a,b){Actor.call(this);this.person=a;this.other=b;this.createFillStyle()};$jscomp.inherits(Relationship,Actor);Relationship.prototype.createFillStyle=function(a){a=void 0===a?null:a;var b=this,c=FlexibleView.Instance.ctx;this.height=16;this.fillStyle="rgba(200, 200, 255, 0.7)";this.img=new Image;this.img.onload=function(){b.height=b.img.height;b.fillStyle=c.createPattern(b.img,"repeat-x")};a&&(this.img.src=a)};
Relationship.prototype.calculatePosition=function(){this.bx=this.person.x;this.by=this.person.y;this.ex=this.other.x;this.ey=this.other.y;var a=this.ex-this.bx,b=this.ey-this.by;this.cx=this.bx+a/2;this.cy=this.by+b/2;this.radian=Math.atan2(b,a);this.length=Math.sqrt(a*a+b*b);this.left=(-this.length+1)/2;this.width=this.length-1};
Relationship.prototype.isHit=function(a,b){var c=Field.Instance.spacing;a=this.cx-a/c;var d=this.cy-b/c,e=-this.radian;b=Math.cos(e)*a-Math.sin(e)*d;a=Math.sin(e)*a+Math.cos(e)*d;var c=this.height/c,d=-c/2,e=this.left,f=this.width+e;return this.hit=e<=b&&b<=f&&d<=a&&a<=d+c};
Relationship.prototype.drawAuxiliary=function(a){var b=Field.Instance.spacing,c=this.bx*b,d=this.by*b,e=this.ex*b,f=this.ey*b,g=this.cx*b,b=this.cy*b;a.save();a.strokeStyle="blue";a.beginPath();a.moveTo(c,d);a.lineTo(e,f);a.stroke();a.fillStyle="red";a.beginPath();a.arc(c,d,4,0,2*Math.PI,!1);a.fill();a.beginPath();a.arc(e,f,4,0,2*Math.PI,!1);a.fill();a.beginPath();a.arc(g,b,4,0,2*Math.PI,!1);a.fill();a.restore()};
Relationship.prototype.draw=function(a){this.calculatePosition();var b=Field.Instance.spacing,c=this.left*b,d=-this.height/2,e=this.cx*b,f=this.cy*b,b=this.width*b;a.save();a.translate(e,f);a.rotate(this.radian);a.translate(c,d);a.fillStyle=this.fillStyle;a.fillRect(0,0,b,this.height);this.hit&&(a.fillStyle="rgba(140, 255, 255, 0.5)",a.fillRect(0,0,b,this.height));a.restore()};
Relationship.create=function(a,b,c){b="fused"==a?new FusedRelation(b,c):"close"==a?new CloseRelation(b,c):"distant"==a?new DistantRelation(b,c):"hostile"==a?new HostileRelation(b,c):new Relationship(b,c);b.emotion=a;return b};var CloseRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.close.png")};$jscomp.inherits(CloseRelation,Relationship);CloseRelation.create=Relationship.create;var DistantRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.distant.png")};
$jscomp.inherits(DistantRelation,Relationship);DistantRelation.create=Relationship.create;var FusedRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/ralation.fused.png")};$jscomp.inherits(FusedRelation,Relationship);FusedRelation.create=Relationship.create;var HostileRelation=function(a,b){Relationship.call(this,a,b);this.createFillStyle("img/relation.hostile.png")};$jscomp.inherits(HostileRelation,Relationship);HostileRelation.create=Relationship.create;
document.addEventListener("DOMContentLoaded",function(){new AppMain});var AppMain=function(){this.listDiagram()};AppMain.prototype.listDiagram=function(a){a=new DiagramEntity;var b=document.getElementById("listView");a.list().then(function(a){a.forEach(function(a){a.name=a.documentId;var c=(new ListviewRow(a,a.image)).li;c.addEventListener("click",function(){window.open("diagram/edit/"+a.documentId)});b.appendChild(c)});$(b).listview("refresh")})};
